export default {
  config: {
    locales: [
      // 'ar',
      // 'fr',
      // 'cs',
      // 'de',
      // 'dk',
      // 'es',
      // 'he',
      // 'id',
      // 'it',
      // 'ja',
      // 'ko',
      // 'ms',
      // 'nl',
      // 'no',
      // 'pl',
      // 'pt-BR',
      // 'pt',
      // 'ru',
      // 'sk',
      // 'sv',
      // 'th',
      // 'tr',
      'uk',
      // 'vi',
      // 'zh-Hans',
      // 'zh',
    ],
    translations: {
      'uk' : {
        "Analytics": "Аналітика",
        "Auth.components.Oops.text": "Ваш обліковий запис призупинено.",
        "Auth.components.Oops.text.admin": "Якщо це помилка, зверніться до адміністратора.",
        "Auth.components.Oops.title": "Ой...",
        "Auth.form.active.label": "Активний",
        "Auth.form.button.forgot-password": "Відправити email",
        "Auth.form.button.go-home": "ПОВЕРНУТИСЯ ДОДОМУ",
        "Auth.form.button.login": "Логін",
        "Auth.form.button.login.providers.error": "Ми не можемо підключити вас через вибраного провайдера.",
        "Auth.form.button.login.strapi": "Увійдіть через Strapi",
        "Auth.form.button.password-recovery": "Відновлення паролю",
        "Auth.form.button.register": "Давайте розпочнемо",
        "Auth.form.confirmPassword.label": "Підтвердьте пароль",
        "Auth.form.currentPassword.label": "Поточний пароль",
        "Auth.form.email.label": "Email",
        "Auth.form.email.placeholder": "напр. kai@doe.com",
        "Auth.form.error.blocked": "Ваш обліковий запис заблоковано адміністратором.",
        "Auth.form.error.code.provide": "Надано неправильний код.",
        "Auth.form.error.confirmed": "Email вашого облікового запису не підтверджена.",
        "Auth.form.error.email.invalid": "Цей email недійсний.",
        "Auth.form.error.email.provide": "Будь ласка, вкажіть своє ім'я користувача або свій email.",
        "Auth.form.error.email.taken": "Email вже зайнятий.",
        "Auth.form.error.invalid": "Недійсний ідентифікатор або пароль.",
        "Auth.form.error.params.provide": "Надано неправильні параметри.",
        "Auth.form.error.password.format": "Ваш пароль не може містити символ `$` більше трьох разів.",
        "Auth.form.error.password.local": "Цей користувач ніколи не встановлював локальний пароль, увійдіть через провайдера, який використовувався під час створення облікового запису.",
        "Auth.form.error.password.matching": "Паролі не співпадають.",
        "Auth.form.error.password.provide": "Будь ласка, введіть свій пароль.",
        "Auth.form.error.ratelimit": "Забагато спроб. Повторіть спробу через хвилину.",
        "Auth.form.error.user.not-exist": "Цього email не існує.",
        "Auth.form.error.username.taken": "Таке ім'я вже використовується.",
        "Auth.form.firstname.label": "Ім'я",
        "Auth.form.firstname.placeholder": "напр. Олег",
        "Auth.form.forgot-password.email.label": "Введіть ваш email",
        "Auth.form.forgot-password.email.label.success": "Email успішно надіслано",
        "Auth.form.lastname.label": "Прізвище",
        "Auth.form.lastname.placeholder": "напр. Петренко",
        "Auth.form.password.hide-password": "Приховати пароль",
        "Auth.form.password.hint": "Має бути принаймні 8 символів, 1 велика, 1 нижня та 1 цифра",
        "Auth.form.password.show-password": "Показати пароль",
        "Auth.form.register.news.label": "Повідомляти мені про нові функції та майбутні вдосконалення (цим ви приймаєте {terms} і {policy}).",
        "Auth.form.register.subtitle": "Облікові дані використовуються лише для автентифікації в Strapi. Усі збережені дані будуть зберігатися у вашій базі даних.",
        "Auth.form.rememberMe.label": "Запам'ятати мене",
        "Auth.form.username.label": "Ім'я користувача",
        "Auth.form.username.placeholder": "напр. Олег_Петренко",
        "Auth.form.welcome.subtitle": "Увійдіть у свій обліковий запис Strapi",
        "Auth.form.welcome.title": "Ласкаво просимо до Strapi!",
        "Auth.link.forgot-password": "Забули свій пароль?",
        "Auth.link.ready": "Готові до входу?",
        "Auth.link.signin": "Увійти",
        "Auth.link.signin.account": "Вже маєте аккаунт?",
        "Auth.login.sso.divider": "Або увійдіти за допомогою",
        "Auth.login.sso.loading": "Завантаження провайдерів...",
        "Auth.login.sso.subtitle": "Увійдіть у свій обліковий запис через SSO",
        "Auth.privacy-policy-agreement.policy": "політика конфіденційності",
        "Auth.privacy-policy-agreement.terms": "умови",
        "Auth.reset-password.title": "Скинути пароль",
        "Content Manager": "Менеджер Вмісту",
        "Content Type Builder": "Конструктор Типів Вмісту",
        "Documentation": "Документація",
        "Email": "Email",
        "Files Upload": "Завантаження файлів",
        "HomePage.helmet.title": "Домашня сторінка",
        "HomePage.roadmap": "Перегляньте нашу дорожню карту",
        "HomePage.welcome.congrats": "Вітаємо!",
        "HomePage.welcome.congrats.content": "Ви ввійшли як перший адміністратор. Щоб дізнатися про потужні функції Strapi,",
        "HomePage.welcome.congrats.content.bold": "ми рекомендуємо вам створити свій перший тип колекції.",
        "Media Library": "Медіатека",
        "New entry": "Новий запис",
        "Password": "Пароль",
        "Provider": "Провайдер",
        "ResetPasswordToken": "Скинути токен пароля",
        "Role": "Роль",
        "Roles & Permissions": "Ролі та Дозволи",
        "Roles.ListPage.notification.delete-all-not-allowed": "Деякі ролі не вдалося видалити, оскільки вони пов’язані з користувачами",
        "Roles.ListPage.notification.delete-not-allowed": "Роль не можна видалити, якщо вона пов’язана з користувачами",
        "Roles.RoleRow.select-all": "Виберіть {name} для групових дій",
        "Roles.RoleRow.user-count": "{number, plural, =0 {# user} one {# user} other {# users}}",
        "Roles.components.List.empty.withSearch": "Немає ролі, що відповідає пошуку ({search})...",
        "Settings.PageTitle": "Налаштування — {name}",
        "Settings.apiTokens.ListView.headers.createdAt": "Створено в",
        "Settings.apiTokens.ListView.headers.description": "Опис",
        "Settings.apiTokens.ListView.headers.lastUsedAt": "Останнє використання",
        "Settings.apiTokens.ListView.headers.name": "Ім'я",
        "Settings.apiTokens.ListView.headers.type": "Тип токену",
        "Settings.apiTokens.addFirstToken": "Додайте свій перший токен API",
        "Settings.apiTokens.addNewToken": "Додати новий API токен",
        "Settings.apiTokens.create": "Створити новий API токен",
        "Settings.apiTokens.createPage.BoundRoute.title": "Маршрут до",
        "Settings.apiTokens.createPage.permissions.description": "Нижче наведено лише дії, пов’язані з маршрутом.",
        "Settings.apiTokens.createPage.permissions.header.hint": "Виберіть дії програми або дії плагіна та клацніть піктограму шестерінки, щоб відобразити прив’язаний маршрут",
        "Settings.apiTokens.createPage.permissions.header.title": "Розширені налаштування",
        "Settings.apiTokens.createPage.permissions.title": "Дозволи",
        "Settings.apiTokens.createPage.title": "Створити токен API",
        "Settings.apiTokens.description": "Список згенерованих токенів для використання API",
        "Settings.apiTokens.emptyStateLayout": "У вас ще немає вмісту...",
        "Settings.apiTokens.regenerate": "Згенерувати заново",
        "Settings.apiTokens.title": "API токени",
        "Settings.application.customization": "Кастомізація",
        "Settings.application.customization.auth-logo.carousel-hint": "Замініть логотип на сторінках автентифікації",
        "Settings.application.customization.carousel-hint": "Змінити логотип панелі адміністратора (максимальний розмір: {dimension}x{dimension}, максимальний розмір файлу: {size}KB)",
        "Settings.application.customization.carousel-slide.label": "Логотип слайд",
        "Settings.application.customization.carousel.auth-logo.title": "Логотип Auth",
        "Settings.application.customization.carousel.change-action": "Змінити логотип",
        "Settings.application.customization.carousel.menu-logo.title": "Логотип меню",
        "Settings.application.customization.carousel.reset-action": "Скинути логотип",
        "Settings.application.customization.carousel.title": "Логотип",
        "Settings.application.customization.menu-logo.carousel-hint": "Замінити логотип у головній навігації",
        "Settings.application.customization.modal.cancel": "Скасувати",
        "Settings.application.customization.modal.pending": "Логотип очікує на розгляд",
        "Settings.application.customization.modal.pending.card-badge": "зображення",
        "Settings.application.customization.modal.pending.choose-another": "Виберіть інший логотип",
        "Settings.application.customization.modal.pending.subtitle": "Керуйте вибраним логотипом перед його завантаженням",
        "Settings.application.customization.modal.pending.title": "Логотип готовий до завантаження",
        "Settings.application.customization.modal.pending.upload": "Завантажити логотип",
        "Settings.application.customization.modal.tab.label": "Як ви хочете завантажити свої ресурси?",
        "Settings.application.customization.modal.upload": "Завантажити логотип",
        "Settings.application.customization.modal.upload.cta.browse": "Перегляд файлів",
        "Settings.application.customization.modal.upload.drag-drop": "Перетягніть сюди або",
        "Settings.application.customization.modal.upload.error-format": "Завантажено неправильний формат (підтримуються лише формати: jpeg, jpg, png, svg).",
        "Settings.application.customization.modal.upload.error-network": "Помилка мережі",
        "Settings.application.customization.modal.upload.error-size": "Завантажений файл завеликий (максимальний розмір: {dimension}x{dimension}, максимальний розмір файлу: {size}KB)",
        "Settings.application.customization.modal.upload.file-validation": "Максимальний розмір: {dimension}x{dimension}, максимальний розмір: {size}KB",
        "Settings.application.customization.modal.upload.from-computer": "З комп'ютера",
        "Settings.application.customization.modal.upload.from-url": "З URL",
        "Settings.application.customization.modal.upload.from-url.input-label": "URL",
        "Settings.application.customization.modal.upload.next": "Далі",
        "Settings.application.customization.size-details": "Максимальний розмір: {dimension}×{dimension}, максимальний розмір файлу: {size}KB",
        "Settings.application.description": "Глобальна інформація адміністративної панелі",
        "Settings.application.edition-title": "поточний план",
        "Settings.application.ee-or-ce": "{communityEdition, select, true {Community Edition} other {Enterprise Edition}}",
        "Settings.application.ee.admin-seats.add-seats": "{isHostedOnStrapiCloud, select, true {Add seats} other {Contact sales}}",
        "Settings.application.ee.admin-seats.at-limit-tooltip": "На межі: додайте місця, щоб запросити більше користувачів",
        "Settings.application.ee.admin-seats.count": "<text>{enforcementUserCount}</text>/{permittedSeats}",
        "Settings.application.get-help": "Отримати допомогу",
        "Settings.application.link-pricing": "Переглянути всі тарифні плани",
        "Settings.application.link-upgrade": "Оновіть панель адміністратора",
        "Settings.application.node-version": "node версія",
        "Settings.application.strapi-version": "Strapi версія",
        "Settings.application.strapiVersion": "Strapi версія",
        "Settings.application.title": "Огляд",
        "Settings.error": "Помилка",
        "Settings.global": "Глобальні налаштування",
        "Settings.permissions": "Панель адміністрування",
        "Settings.permissions.auditLogs.action": "Дія",
        "Settings.permissions.auditLogs.admin.auth.success": "Логін адміністратора",
        "Settings.permissions.auditLogs.admin.logout": "Вихід адміністратора",
        "Settings.permissions.auditLogs.component.create": "Створити компонент",
        "Settings.permissions.auditLogs.component.delete": "Видалити компонент",
        "Settings.permissions.auditLogs.component.update": "Оновити компонент",
        "Settings.permissions.auditLogs.content-type.create": "Створення типу вмісту",
        "Settings.permissions.auditLogs.content-type.delete": "Видалити тип вмісту",
        "Settings.permissions.auditLogs.content-type.update": "Оновити тип вмісту",
        "Settings.permissions.auditLogs.date": "Дата",
        "Settings.permissions.auditLogs.details": "Деталі журналу",
        "Settings.permissions.auditLogs.entry.create": "Створити запис{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.entry.delete": "Видалити запис{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.entry.publish": "Опублікувати запис {model, select, undefined {} other {({model})}}",
        "Settings.permissions.auditLogs.entry.unpublish": "Скасувати публікацію запису{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.entry.update": "Оновити запис{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.filters.combobox.aria-label": "Знайдіть і виберіть параметр для фільтрування",
        "Settings.permissions.auditLogs.listview.header.subtitle": "Журнали всіх дій, які відбувалися у вашому оточенні",
        "Settings.permissions.auditLogs.media.create": "Створити медіа",
        "Settings.permissions.auditLogs.media.delete": "Видалити медіа",
        "Settings.permissions.auditLogs.media.update": "Оновити медіа",
        "Settings.permissions.auditLogs.payload": "Корисне навантаження",
        "Settings.permissions.auditLogs.permission.create": "Створити дозвіл",
        "Settings.permissions.auditLogs.permission.delete": "Видалити дозвіл",
        "Settings.permissions.auditLogs.permission.update": "Оновити дозвіл",
        "Settings.permissions.auditLogs.role.create": "Створити роль",
        "Settings.permissions.auditLogs.role.delete": "Видалити роль",
        "Settings.permissions.auditLogs.role.update": "Оновити роль",
        "Settings.permissions.auditLogs.user": "Користувач",
        "Settings.permissions.auditLogs.user.create": "Створити користувача",
        "Settings.permissions.auditLogs.user.delete": "Видалити користувача",
        "Settings.permissions.auditLogs.user.fullname": "{firstname} {lastname}",
        "Settings.permissions.auditLogs.user.update": "Оновити користувача",
        "Settings.permissions.auditLogs.userId": "Ідентифікатор користувача",
        "Settings.permissions.category": "Налаштування дозволів для {category}",
        "Settings.permissions.category.plugins": "Налаштування дозволів для розширення {category}",
        "Settings.permissions.conditions.anytime": "Будь-коли",
        "Settings.permissions.conditions.apply": "Застосувати",
        "Settings.permissions.conditions.can": "Може",
        "Settings.permissions.conditions.conditions": "Умови",
        "Settings.permissions.conditions.define-conditions": "Визначити умови",
        "Settings.permissions.conditions.links": "Посилання",
        "Settings.permissions.conditions.no-actions": "Спочатку вам потрібно вибрати дії (створити, прочитати, оновити, ...), перш ніж визначати умови для них.",
        "Settings.permissions.conditions.none-selected": "Будь-коли",
        "Settings.permissions.conditions.or": "АБО",
        "Settings.permissions.conditions.when": "Коли",
        "Settings.permissions.select-all-by-permission": "Виберіть усі дозволи {label}",
        "Settings.permissions.select-by-permission": "Виберіть дозвіл {label}",
        "Settings.permissions.users.active": "Активний",
        "Settings.permissions.users.create": "Запросити нового користувача",
        "Settings.permissions.users.email": "Email",
        "Settings.permissions.users.firstname": "Ім'я",
        "Settings.permissions.users.form.sso": "Підключитися через SSO",
        "Settings.permissions.users.form.sso.description": "Якщо ввімкнено (ON), користувачі можуть входити через SSO",
        "Settings.permissions.users.inactive": "Неактивний",
        "Settings.permissions.users.lastname": "Прізвище",
        "Settings.permissions.users.listview.header.subtitle": "Усі користувачі, які мають доступ до панелі адміністратора Strapi",
        "Settings.permissions.users.roles": "Ролі",
        "Settings.permissions.users.strapi-author": "Автор",
        "Settings.permissions.users.strapi-editor": "Редактор",
        "Settings.permissions.users.strapi-super-admin": "Супер адміністратор",
        "Settings.permissions.users.tabs.label": "Вкладки Дозволи",
        "Settings.permissions.users.user-status": "Статус користувача",
        "Settings.permissions.users.username": "Ім'я користувача",
        "Settings.profile.form.notify.data.loaded": "Дані вашого профілю завантажено",
        "Settings.profile.form.section.experience.clear.select": "Очистіть вибрану мову інтерфейсу",
        "Settings.profile.form.section.experience.here": "тут",
        "Settings.profile.form.section.experience.interfaceLanguage": "Мова інтерфейсу",
        "Settings.profile.form.section.experience.interfaceLanguage.hint": "Це відображатиме лише ваш власний інтерфейс вибраною мовою.",
        "Settings.profile.form.section.experience.interfaceLanguageHelp": "Зміни налаштувань стосуватимуться лише вас. Більше інформації доступно {тут}.",
        "Settings.profile.form.section.experience.mode.hint": "Відображає ваш інтерфейс у вибраному режимі.",
        "Settings.profile.form.section.experience.mode.label": "Режим інтерфейсу",
        "Settings.profile.form.section.experience.mode.option-label": "Режим {name}",
        "Settings.profile.form.section.experience.title": "Досвід",
        "Settings.profile.form.section.helmet.title": "Профіль користувача",
        "Settings.profile.form.section.profile.page.title": "Сторінка профілю",
        "Settings.review-workflows.page.title": "Перегляд робочих процесів",
        "Settings.review-workflows.page.subtitle": "{count, plural, one {# stage} other {# stages}}",
        "Settings.review-workflows.page.isLoading": "Робочий процес завантажується",
        "Settings.review-workflows.page.delete.confirm.body": "Усі записи, призначені видаленим етапам, буде перенесено на попередній етап. Ви впевнені, що хочете зберегти?",
        "Settings.review-workflows.stage.name.label": "Назва етапу",
        "Settings.roles.create.description": "Визначте права, надані ролі",
        "Settings.roles.create.title": "Створіть роль",
        "Settings.roles.created": "Роль створено",
        "Settings.roles.edit.title": "Редагувати роль",
        "Settings.roles.form.button.users-with-role": "{number, plural, =0 {# users} one {# user} other {# users}} з цією роллю",
        "Settings.roles.form.created": "Створено",
        "Settings.roles.form.description": "Назва та опис ролі",
        "Settings.roles.form.permission.property-label": "{label} дозволи",
        "Settings.roles.form.permissions.attributesPermissions": "Дозволи полів",
        "Settings.roles.form.permissions.create": "Створити",
        "Settings.roles.form.permissions.delete": "Видалити",
        "Settings.roles.form.permissions.publish": "Опублікувати",
        "Settings.roles.form.permissions.read": "Читати",
        "Settings.roles.form.permissions.update": "Оновити",
        "Settings.roles.list.button.add": "Додати нову роль",
        "Settings.roles.list.description": "Список ролей",
        "Settings.roles.title.singular": "роль",
        "Settings.sso.description": "Налаштуйте параметри функції єдиного входу.",
        "Settings.sso.form.defaultRole.description": "Це приєднає нового автентифікованого користувача до вибраної ролі",
        "Settings.sso.form.defaultRole.description-not-allowed": "Щоб читати ролі адміністратора, потрібно мати дозвіл",
        "Settings.sso.form.defaultRole.label": "Роль за замовчуванням",
        "Settings.sso.form.registration.description": "Створіть нового користувача для входу в систему SSO, якщо обліковий запис не існує",
        "Settings.sso.form.registration.label": "Автоматична реєстрація",
        "Settings.sso.title": "Єдиний вхід",
        "Settings.tokens.Button.cancel": "Скасувати",
        "Settings.tokens.Button.regenerate": "Створити заново",
        "Settings.tokens.ListView.headers.createdAt": "Створено в",
        "Settings.tokens.ListView.headers.description": "Опис",
        "Settings.tokens.ListView.headers.lastUsedAt": "Востаннє використано",
        "Settings.tokens.ListView.headers.name": "Ім'я",
        "Settings.tokens.RegenerateDialog.title": "Створити токен заново",
        "Settings.tokens.copy.editMessage": "З міркувань безпеки ви можете побачити свій токен лише один раз.",
        "Settings.tokens.copy.editTitle": "Цей токен більше не доступний.",
        "Settings.tokens.copy.lastWarning": "Обов’язково скопіюйте цей токен, ви більше не зможете його побачити!",
        "Settings.tokens.duration.30-days": "30 днів",
        "Settings.tokens.duration.7-days": "7 днів",
        "Settings.tokens.duration.90-days": "90 днів",
        "Settings.tokens.duration.expiration-date": "Термін придатності",
        "Settings.tokens.duration.unlimited": "Необмежений",
        "Settings.tokens.form.description": "Опис",
        "Settings.tokens.form.duration": "Тривалість токена",
        "Settings.tokens.form.name": "Ім'я",
        "Settings.tokens.form.type": "Тип токена",
        "Settings.tokens.notification.copied": "Токен скопійовано в буфер обміну.",
        "Settings.tokens.popUpWarning.message": "Ви впевнені, що бажаєте створити заново цей токен?",
        "Settings.tokens.regenerate": "Створити заново",
        "Settings.tokens.types.custom": "Кастомний",
        "Settings.tokens.types.full-access": "Повний доступ",
        "Settings.tokens.types.read-only": "Лише для читання",
        "Settings.transferTokens.ListView.headers.type": "Тип токена",
        "Settings.transferTokens.addFirstToken": "Додайте свій перший токен передачі",
        "Settings.transferTokens.addNewToken": "Додайте новий токен передачі",
        "Settings.transferTokens.create": "Створіть новий токен передачі",
        "Settings.transferTokens.createPage.title": "Створіть токен передачі",
        "Settings.transferTokens.description": "Список згенерованих токенів передачі",
        "Settings.transferTokens.emptyStateLayout": "У вас ще немає вмісту...",
        "Settings.transferTokens.title": "Токени передачі",
        "Settings.webhooks.create": "Створіть вебхук",
        "Settings.webhooks.create.header": "Створити новий заголовок",
        "Settings.webhooks.created": "Вебхук створено",
        "Settings.webhooks.event.publish-tooltip": "Ця подія існує лише для вмісту з увімкненою системою Draft/Publish",
        "Settings.webhooks.events.create": "Створити",
        "Settings.webhooks.events.update": "Оновити",
        "Settings.webhooks.form.events": "Події",
        "Settings.webhooks.form.headers": "Заголовки",
        "Settings.webhooks.form.url": "URL",
        "Settings.webhooks.headers.remove": "Видалити рядок заголовка {number}",
        "Settings.webhooks.key": "Ключ",
        "Settings.webhooks.list.button.add": "Створити новий вебхук",
        "Settings.webhooks.list.description": "Отримувати сповіщення про зміни POST",
        "Settings.webhooks.list.empty.description": "Вебхуки не знайдено",
        "Settings.webhooks.list.empty.link": "Перегляньте нашу документацію",
        "Settings.webhooks.list.empty.title": "Вебхуків ще немає",
        "Settings.webhooks.list.th.actions": "дії",
        "Settings.webhooks.list.th.status": "статус",
        "Settings.webhooks.singular": "вебхук",
        "Settings.webhooks.title": "Веб-хуки",
        "Settings.webhooks.to.delete": "{webhooksToDeleteLength, plural, one {# asset} other {# assets}} вибрано",
        "Settings.webhooks.trigger": "Тригер",
        "Settings.webhooks.trigger.cancel": "Скасувати тригер",
        "Settings.webhooks.trigger.pending": "В очікуванні…",
        "Settings.webhooks.trigger.save": "Будь ласка, збережіть для запуску",
        "Settings.webhooks.trigger.success": "Успіх!",
        "Settings.webhooks.trigger.success.label": "Тригер вдався",
        "Settings.webhooks.trigger.test": "Тест-тригер",
        "Settings.webhooks.trigger.title": "Зберегти перед запуском",
        "Settings.webhooks.value": "Значення",
        "Usecase.back-end": "Back-end розробник",
        "Usecase.button.skip": "Пропустити це запитання",
        "Usecase.content-creator": "Творець вмісту",
        "Usecase.front-end": "Front-end розробник",
        "Usecase.full-stack": "Full-stack розробник",
        "Usecase.input.work-type": "Який вид роботи ви виконуєте?",
        "Usecase.notification.success.project-created": "Проект успішно створено",
        "Usecase.other": "Інше",
        "Usecase.title": "Розкажіть нам трохи більше про себе",
        "Username": "Ім'я користувача",
        "Users & Permissions": "Користувачі та дозволи",
        "Users": "Користувачі",
        "Users.components.List.empty": "Користувачів немає...",
        "Users.components.List.empty.withFilters": "Немає користувачів із застосованими фільтрами...",
        "Users.components.List.empty.withSearch": "Немає користувачів, які відповідають запиту ({search})...",
        "admin.pages.MarketPlacePage.filters.categories": "Категорії",
        "admin.pages.MarketPlacePage.filters.categoriesSelected": "{count, plural, =0 {No categories} one {# category} other {# categories}} вибрано",
        "admin.pages.MarketPlacePage.filters.collections": "Колекції",
        "admin.pages.MarketPlacePage.filters.collectionsSelected": "{count, plural, =0 {No Collections} one {# Collection} other {# Collections}} вибрано",
        "admin.pages.MarketPlacePage.helmet": "Маркетплейс - Розширення",
        "admin.pages.MarketPlacePage.missingPlugin.description": "Скажіть нам, яке розширення ви шукаєте, і ми повідомимо розробників розширень нашої спільноти, якщо вони шукатимуть натхнення!",
        "admin.pages.MarketPlacePage.missingPlugin.title": "Відсутнє розширення?",
        "admin.pages.MarketPlacePage.offline.subtitle": "Щоб отримати доступ до Strapi Market, потрібно підключитися до Інтернету.",
        "admin.pages.MarketPlacePage.offline.title": "Ви в режимі офлайн",
        "admin.pages.MarketPlacePage.plugin.copy": "Копіювати команду встановлення",
        "admin.pages.MarketPlacePage.plugin.copy.success": "Команда встановлення готова до вставлення у ваш термінал",
        "admin.pages.MarketPlacePage.plugin.downloads": "Це розширення має {downloadsCount} щотижневих завантажень",
        "admin.pages.MarketPlacePage.plugin.githubStars": "Це розширення позначено зірочкою {starsCount} разів на GitHub",
        "admin.pages.MarketPlacePage.plugin.info": "Дізнатись більше",
        "admin.pages.MarketPlacePage.plugin.info.label": "Дізнатись більше про {pluginName}",
        "admin.pages.MarketPlacePage.plugin.info.text": "Більше",
        "admin.pages.MarketPlacePage.plugin.installed": "Встановлено",
        "admin.pages.MarketPlacePage.plugin.tooltip.madeByStrapi": "Зроблено Strapi",
        "admin.pages.MarketPlacePage.plugin.tooltip.verified": "Розширення перевірено Strapi",
        "admin.pages.MarketPlacePage.plugin.version": "Оновіть свою версію Strapi: \"{strapiAppVersion}\" до: \"{versionRange}\"",
        "admin.pages.MarketPlacePage.plugin.version.null": "Не вдалося перевірити сумісність із вашою версією Strapi: \"{strapiAppVersion}\"",
        "admin.pages.MarketPlacePage.plugins": "Розширення",
        "admin.pages.MarketPlacePage.provider.downloads": "Цей провайдер має {downloadsCount} щотижневих завантажень",
        "admin.pages.MarketPlacePage.provider.githubStars": "Цей провайдер позначено зірочкою {starsCount} на GitHub",
        "admin.pages.MarketPlacePage.providers": "Провайдери",
        "admin.pages.MarketPlacePage.search.clear": "Очистити пошук",
        "admin.pages.MarketPlacePage.search.empty": "Немає результату для \"{target}\"",
        "admin.pages.MarketPlacePage.search.placeholder": "Пошук",
        "admin.pages.MarketPlacePage.sort.alphabetical": "Алфавітний порядок",
        "admin.pages.MarketPlacePage.sort.alphabetical.selected": "Сортувати в алфавітному порядку",
        "admin.pages.MarketPlacePage.sort.githubStars": "Кількість зірок GitHub",
        "admin.pages.MarketPlacePage.sort.githubStars.selected": "Сортувати за зірками GitHub",
        "admin.pages.MarketPlacePage.sort.newest": "Найновіший",
        "admin.pages.MarketPlacePage.sort.newest.selected": "Сортувати за найновішим",
        "admin.pages.MarketPlacePage.sort.npmDownloads": "Кількість завантажень",
        "admin.pages.MarketPlacePage.sort.npmDownloads.selected": "Сортувати за завантаженнями npm",
        "admin.pages.MarketPlacePage.submit.plugin.link": "Надіслати розширення",
        "admin.pages.MarketPlacePage.submit.provider.link": "Надіслати провайдера",
        "admin.pages.MarketPlacePage.subtitle": "Отримати більше від Strapi",
        "admin.pages.MarketPlacePage.tab-group.label": "Розширення та постачальники для Strapi",
        "anErrorOccurred": "Ой! Щось пішло не так. Будь ласка спробуйте ще раз.",
        "app.component.CopyToClipboard.label": "Скопіювати в буфер обміну",
        "app.component.search.label": "Шукати {target}",
        "app.component.table.duplicate": "Дублювати {target}",
        "app.component.table.edit": "Редагувати {target}",
        "app.component.table.read": "Читати {target}",
        "app.component.table.select.one-entry": "Обрати {target}",
        "app.component.table.view": "{target} деталі",
        "app.components.BlockLink.blog": "Блог",
        "app.components.BlockLink.blog.content": "Читайте останні новини про Strapi та екосистему.",
        "app.components.BlockLink.cloud": "Strapi хмара",
        "app.components.BlockLink.cloud.content": "Повністю комбінована платформа для спільної роботи для підвищення швидкості вашої команди.",
        "app.components.BlockLink.code": "Приклади коду",
        "app.components.BlockLink.code.content": "Навчайтеся, тестуючи реальні проекти, розроблені спільнотою.",
        "app.components.BlockLink.documentation.content": "Відкрийте для себе основні поняття, посібники та інструкції.",
        "app.components.BlockLink.tutorial": "Підручники",
        "app.components.BlockLink.tutorial.content": "Дотримуйтеся покрокових інструкцій, щоб використовувати та налаштовувати Strapi.",
        "app.components.Button.cancel": "Скасувати",
        "app.components.Button.confirm": "Підтвердити",
        "app.components.Button.reset": "Скинути",
        "app.components.ComingSoonPage.comingSoon": "Незабаром",
        "app.components.ConfirmDialog.title": "Підтвердження",
        "app.components.DownloadInfo.download": "Виконується завантаження...",
        "app.components.DownloadInfo.text": "Це може зайняти хвилину. Дякуємо за Ваше терпіння.",
        "app.components.EmptyAttributes.title": "Полів ще немає",
        "app.components.EmptyStateLayout.content-document": "Контенту не знайдено",
        "app.components.EmptyStateLayout.content-permissions": "Ви не маєте прав доступу до цього вмісту",
        "app.components.GuidedTour.CM.create.content": "<p>Створюйте весь вміст і керуйте ним тут, у Менеджері вмісту.</p><p>Наприклад: продовжуючи приклад веб-сайту блогу, можна написати статтю, зберегти та опублікувати її як завгодно.</p>< p>💡 Коротка порада — не забудьте натиснути «Опублікувати» створеного вмісту.</p>",
        "app.components.GuidedTour.CM.create.title": "⚡️ Створити контент",
        "app.components.GuidedTour.CM.success.content": "<p>Чудово, залишився останній крок!</p><b>🚀 Перегляньте вміст у дії</b>",
        "app.components.GuidedTour.CM.success.cta.title": "Протестувати API",
        "app.components.GuidedTour.CM.success.title": "Крок 2: Завершено ✅",
        "app.components.GuidedTour.CTB.create.content": "<p>Типи колекцій допомагають керувати декількома записами, окремі типи підходять для керування лише одним записом.</p> <p>Наприклад: для веб-сайту блогу статті будуть типом колекції, тоді як домашня сторінка буде одним типом. </p>",
        "app.components.GuidedTour.CTB.create.cta.title": "Створення типу колекції",
        "app.components.GuidedTour.CTB.create.title": "🧠 Створіть перший тип колекції",
        "app.components.GuidedTour.CTB.success.content": "<p>Чудово!</p><b>⚡️ Чим би ви хотіли поділитися зі світом?</b>",
        "app.components.GuidedTour.CTB.success.title": "Крок 1: Завершено ✅",
        "app.components.GuidedTour.apiTokens.create.content": "<p>Згенеруйте тут токен автентифікації та отримайте щойно створений вміст.</p>",
        "app.components.GuidedTour.apiTokens.create.cta.title": "Згенерувати API токен",
        "app.components.GuidedTour.apiTokens.create.title": "🚀 Дивіться вміст у дії",
        "app.components.GuidedTour.apiTokens.success.content": "<p>Перегляньте вміст у дії, зробивши запит HTTP:</p><ul><li><p>На цю URL-адресу: <light>https://'<'YOUR_DOMAIN'>'/api/'<' YOUR_CT'>'</light></p></li><li><p>Із заголовком: <light>Авторизація: носій '<'YOUR_API_TOKEN'>'</light></p></li ></ul><p>Додаткові способи взаємодії з вмістом див. у <documentationLink>документації</documentationLink>.</p>",
        "app.components.GuidedTour.apiTokens.success.cta.title": "Повернутися на головну",
        "app.components.GuidedTour.apiTokens.success.title": "Крок 3: Завершено ✅",
        "app.components.GuidedTour.create-content": "Створити контент",
        "app.components.GuidedTour.home.CM.title": "⚡️ Чим би ви хотіли поділитися зі світом?",
        "app.components.GuidedTour.home.CTB.cta.title": "Перейдіть до Content type Builder",
        "app.components.GuidedTour.home.CTB.title": "🧠 Побудуйте структуру контенту",
        "app.components.GuidedTour.home.apiTokens.cta.title": "Протестувати API",
        "app.components.GuidedTour.skip": "Пропустити тур",
        "app.components.GuidedTour.title": "3 кроки, щоб розпочати",
        "app.components.HomePage.button.blog": "Дивіться більше в блозі",
        "app.components.HomePage.community": "Приєднуйтеся до спільноти",
        "app.components.HomePage.community.content": "Обговорюйте з членами команди, співавторами та розробниками на різних каналах.",
        "app.components.HomePage.create": "Створіть свій перший тип вмісту",
        "app.components.HomePage.roadmap": "Перегляньте нашу дорожню карту",
        "app.components.HomePage.welcome": "Ласкаво просимо на борт 👋",
        "app.components.HomePage.welcome.again": "Ласкаво просимо 👋",
        "app.components.HomePage.welcomeBlock.content": "Вітаємо! Ви увійшли як перший адміністратор. Щоб відкрити для себе потужні функції Strapi, ми рекомендуємо вам створити свій перший тип вмісту!",
        "app.components.HomePage.welcomeBlock.content.again": "Сподіваємось, ви досягаєте успіхів у своєму проекті! Не соромтеся читати останні новини про Strapi. Ми докладаємо всіх зусиль, щоб покращити продукт на основі ваших відгуків.",
        "app.components.HomePage.welcomeBlock.content.issues": "питань.",
        "app.components.HomePage.welcomeBlock.content.raise": " або підняти ",
        "app.components.ImgPreview.hint": "Перетягніть файл у цю область або {browse} файл, який потрібно завантажити",
        "app.components.ImgPreview.hint.browse": "переглядати",
        "app.components.InputFile.newFile": "Додати новий файл",
        "app.components.InputFileDetails.open": "Відкрити у новій вкладці",
        "app.components.InputFileDetails.originalName": "Оригінальна назва:",
        "app.components.InputFileDetails.remove": "Видалити цей файл",
        "app.components.InputFileDetails.size": "Розмір:",
        "app.components.InstallPluginPage.Download.description": "Завантаження та встановлення розширення може зайняти декілька секунд",
        "app.components.InstallPluginPage.Download.title": "Завантаження...",
        "app.components.InstallPluginPage.description": "Розширюйте свою програму без зусиль.",
        "app.components.LeftMenu.collapse": "Згорнути навігаційну панель",
        "app.components.LeftMenu.expand": "Розгорнути навігаційну панель",
        "app.components.LeftMenu.general": "Загальний",
        "app.components.LeftMenu.logo.alt": "Логотип програми",
        "app.components.LeftMenu.logout": "Вихід",
        "app.components.LeftMenu.navbrand.title": "Адмін панель Strapi",
        "app.components.LeftMenu.navbrand.workplace": "Робоче місце",
        "app.components.LeftMenu.plugins": "Розширення",
        "app.components.LeftMenuFooter.help": "Допомога",
        "app.components.LeftMenuFooter.poweredBy": "На основі ",
        "app.components.LeftMenuLinkContainer.collectionTypes": "Типи колекцій",
        "app.components.LeftMenuLinkContainer.configuration": "Налаштування",
        "app.components.LeftMenuLinkContainer.general": "Загальний",
        "app.components.LeftMenuLinkContainer.noPluginsInstalled": "Розширень поки що не встановлено",
        "app.components.LeftMenuLinkContainer.plugins": "Розширення",
        "app.components.LeftMenuLinkContainer.singleTypes": "Одиничні типи",
        "app.components.ListPluginsPage.deletePlugin.description": "Видалення розширення може зайняти кілька секунд.",
        "app.components.ListPluginsPage.deletePlugin.title": "Видалення",
        "app.components.ListPluginsPage.description": "Список встановлених розширень у проекті.",
        "app.components.ListPluginsPage.helmet.title": "Список розширень",
        "app.components.Logout.logout": "Вихід",
        "app.components.Logout.profile": "Профіль",
        "app.components.MarketplaceBanner": "Відкрийте для себе розширення, створені спільнотою, і багато інших чудових речей, щоб розпочати свій проект, на Strapi Marketplace.",
        "app.components.MarketplaceBanner.image.alt": "Логотип ракети Strapi",
        "app.components.MarketplaceBanner.link": "Перевірте це зараз",
        "app.components.NotFoundPage.back": "Повернутися на головну",
        "app.components.NotFoundPage.description": "Не знайдено",
        "app.components.Official": "Офіційний",
        "app.components.Onboarding.help.button": "Кнопка довідки",
        "app.components.Onboarding.label.completed": "% завершено",
        "app.components.Onboarding.link.build-content": "Створити архітектуру вмісту",
        "app.components.Onboarding.link.manage-content": "Додати вміст і керувати ним",
        "app.components.Onboarding.link.manage-media": "Керувати медіа",
        "app.components.Onboarding.link.more-videos": "Дивитись більше відео",
        "app.components.Onboarding.title": "Відео для початку роботи",
        "app.components.PluginCard.Button.label.download": "Завантажити",
        "app.components.PluginCard.Button.label.install": "Уже встановлено",
        "app.components.PluginCard.PopUpWarning.install.impossible.autoReload.needed": "Необхідно ввімкнути функцію автоматичного перезавантаження. Будь ласка, запустіть свою програму з `yarn develop`.",
        "app.components.PluginCard.PopUpWarning.install.impossible.confirm": "Я зрозумів!",
        "app.components.PluginCard.PopUpWarning.install.impossible.environment": "З міркувань безпеки розширення можна завантажити лише в середовищі розробки.",
        "app.components.PluginCard.PopUpWarning.install.impossible.title": "Завантажити неможливо",
        "app.components.PluginCard.compatible": "Сумісний із вашим додатком",
        "app.components.PluginCard.compatibleCommunity": "Сумісний із спільнотою",
        "app.components.PluginCard.more-details": "Детальніше",
        "app.components.ToggleCheckbox.off-label": "Брехня",
        "app.components.ToggleCheckbox.on-label": "Правда",
        "app.components.Users.MagicLink.connect": "Скопіюйте і поділіться цим посиланням, щоб надати доступ цьому користувачу",
        "app.components.Users.MagicLink.connect.sso": "Перевірити цей зв'язок для користувача, першим підписом може бути зроблено через SSO provider",
        "app.components.Users.ModalCreateBody.block-title.details": "Інформація про користувача",
        "app.components.Users.ModalCreateBody.block-title.roles": "Ролі користувача",
        "app.components.Users.ModalCreateBody.block-title.roles.description": "Користувач може мати одну чи деілька ролей",
        "app.components.Users.SortPicker.button-label": "Сортувати за",
        "app.components.Users.SortPicker.sortby.email_asc": "Email (A до Z)",
        "app.components.Users.SortPicker.sortby.email_desc": "Email (Z до A)",
        "app.components.Users.SortPicker.sortby.firstname_asc": "Ім'я (А до Я)",
        "app.components.Users.SortPicker.sortby.firstname_desc": "Ім'я (Я до А)",
        "app.components.Users.SortPicker.sortby.lastname_asc": "Прізвище (А до Я)",
        "app.components.Users.SortPicker.sortby.lastname_desc": "Прізвище (Я до А)",
        "app.components.Users.SortPicker.sortby.username_asc": "Ім'я користувача (А до Я)",
        "app.components.Users.SortPicker.sortby.username_desc": "Ім'я користувача (Я до А)",
        "app.components.listPlugins.button": "Додати нове розширення",
        "app.components.listPlugins.title.none": "Немає встановлених розширень",
        "app.components.listPluginsPage.deletePlugin.error": "Під час видалення розширення сталася помилка",
        "app.containers.App.notification.error.init": "Під час запиту API сталася помилка",
        "app.containers.AuthPage.ForgotPasswordSuccess.text.contact-admin": "Якщо ви не отримали це посилання, зверніться до свого адміністратора.",
        "app.containers.AuthPage.ForgotPasswordSuccess.text.email": "Отримання посилання для відновлення пароля може зайняти кілька хвилин.",
        "app.containers.AuthPage.ForgotPasswordSuccess.title": "Email надіслано",
        "app.containers.Users.EditPage.form.active.label": "Активний",
        "app.containers.Users.EditPage.header.label": "Редагувати {name}",
        "app.containers.Users.EditPage.header.label-loading": "Редагувати користувача",
        "app.containers.Users.EditPage.roles-bloc-title": "Приписані ролі",
        "app.containers.Users.ModalForm.footer.button-success": "Запросити користувача",
        "app.links.configure-view": "Налаштувати перегляд",
        "app.page.not.found": "Ой! Здається, ми не можемо знайти сторінку, яку ви шукаєте...",
        "app.static.links.cheatsheet": "Шпаргалка",
        "app.utils.SelectOption.defaultMessage": " ",
        "app.utils.add-filter": "Додати фільтр",
        "app.utils.close-label": "Закрити",
        "app.utils.defaultMessage": " ",
        "app.utils.delete": "Видалити",
        "app.utils.duplicate": "Дублювати",
        "app.utils.edit": "Редагувати",
        "app.utils.errors.file-too-big.message": "Файл занадто великий",
        "app.utils.filter-value": "Значення фільтра",
        "app.utils.filters": "Фільтри",
        "app.utils.notify.data-loaded": "{target} завантажено",
        "app.utils.placeholder.defaultMessage": " ",
        "app.utils.publish": "Опублікувати",
        "app.utils.select-all": "Обрати все",
        "app.utils.select-field": "Обрати поле",
        "app.utils.select-filter": "Обрати фільтр",
        "app.utils.unpublish": "Скасувати публікацію",
        "clearLabel": "Очистити",
        "coming.soon": "Цей вміст наразі розробляється та повернеться через кілька тижнів!",
        "component.Input.error.validation.integer": "Значення повинно бути цілим числом",
        "components.AutoReloadBlocker.description": "Запустіть Strapi за допомогою однієї з наступних команд:",
        "components.AutoReloadBlocker.header": "Для цього розширення потрібна функція перезавантаження.",
        "components.ErrorBoundary.title": "Щось пішло не так...",
        "components.FilterOptions.FILTER_TYPES.$contains": "містить (з урахуванням регістру)",
        "components.FilterOptions.FILTER_TYPES.$endsWith": "закінчується на",
        "components.FilterOptions.FILTER_TYPES.$eq": "є",
        "components.FilterOptions.FILTER_TYPES.$gt": "більше ніж",
        "components.FilterOptions.FILTER_TYPES.$gte": "більше ніж або дорівнює",
        "components.FilterOptions.FILTER_TYPES.$lt": "менше ніж",
        "components.FilterOptions.FILTER_TYPES.$lte": "менше ніж або дорівнює",
        "components.FilterOptions.FILTER_TYPES.$ne": "не є",
        "components.FilterOptions.FILTER_TYPES.$notContains": "не містить (з урахуванням регістру)",
        "components.FilterOptions.FILTER_TYPES.$notNull": "не є null",
        "components.FilterOptions.FILTER_TYPES.$null": "є null",
        "components.FilterOptions.FILTER_TYPES.$startsWith": "починається з",
        "components.Input.error.attribute.key.taken": "Це значення уже існує",
        "components.Input.error.attribute.sameKeyAndName": "Не може бути рівним",
        "components.Input.error.attribute.taken": "Назва цього поля уже існує",
        "components.Input.error.contain.lowercase": "Пароль повинен містити як мінімум один символ у нижньому регістрі",
        "components.Input.error.contain.number": "Пароль повинен містити як мінімум одну цифру",
        "components.Input.error.contain.uppercase": "Пароль повинен містити як мінімум один символ у верхньому регістрі",
        "components.Input.error.contentTypeName.taken": "Це ім'я уже існує",
        "components.Input.error.custom-error": "{errorMessage} ",
        "components.Input.error.password.noMatch": "Паролі не збігаються",
        "components.Input.error.validation.email": "Це недійсна електронна адреса",
        "components.Input.error.validation.json": "Це не відповідає формату JSON",
        "components.Input.error.validation.lowercase": "Значення має бути рядком у нижньому регістрі",
        "components.Input.error.validation.max": "Значення завелике.",
        "components.Input.error.validation.maxLength": "Значення задовге.",
        "components.Input.error.validation.min": "Значення занизьке.",
        "components.Input.error.validation.minLength": "Значення закоротке.",
        "components.Input.error.validation.minSupMax": "Не може бути вищим",
        "components.Input.error.validation.regex": "Значення не відповідає регулярному виразу.",
        "components.Input.error.validation.required": "Це значення є обов’язковим.",
        "components.Input.error.validation.unique": "Це значення вже використовується.",
        "components.InputSelect.option.placeholder": "Виберіть тут",
        "components.ListRow.empty": "Немає даних для показу.",
        "components.NotAllowedInput.text": "Немає дозволів на перегляд цього поля",
        "components.OverlayBlocker.description": "Ви використовуєте функцію, яка потребує перезапуску сервера. Зачекайте, доки сервер запрацює.",
        "components.OverlayBlocker.description.serverError": "Сервер повинен був перезавантажитися, будь ласка, перевірте свої журнали в терміналі.",
        "components.OverlayBlocker.title": "Очікування перезапуску...",
        "components.OverlayBlocker.title.serverError": "Перезапуск триває довше, ніж очікувалося",
        "components.PageFooter.select": "Записів на сторінці",
        "components.ProductionBlocker.description": "З метою безпеки ми повинні вимкнути це розширення в інших середовищах.",
        "components.ProductionBlocker.header": "Це розширення доступний лише на стадії розробки.",
        "components.Search.placeholder": "Пошук...",
        "components.TableHeader.sort": "Сортувати за {label}",
        "components.Wysiwyg.ToggleMode.markdown-mode": "Режим розмітки",
        "components.Wysiwyg.ToggleMode.preview-mode": "Режим попереднього перегляду",
        "components.Wysiwyg.collapse": "Згорнути",
        "components.Wysiwyg.selectOptions.H1": "Заголовок H1",
        "components.Wysiwyg.selectOptions.H2": "Заголовок H2",
        "components.Wysiwyg.selectOptions.H3": "Заголовок H3",
        "components.Wysiwyg.selectOptions.H4": "Заголовок H4",
        "components.Wysiwyg.selectOptions.H5": "Заголовок H5",
        "components.Wysiwyg.selectOptions.H6": "Заголовок H6",
        "components.Wysiwyg.selectOptions.title": "Додати заголовок",
        "components.WysiwygBottomControls.charactersIndicators": "символів",
        "components.WysiwygBottomControls.fullscreen": "Розгорнути",
        "components.WysiwygBottomControls.uploadFiles": "Перетягніть файли, вставте їх із буфера обміну або {browse}.",
        "components.WysiwygBottomControls.uploadFiles.browse": "виберіть їх",
        "components.pagination.go-to": "Перейти на сторінку {page}",
        "components.pagination.go-to-next": "Перейти до наступної сторінки",
        "components.pagination.go-to-previous": "Перейти на попередню сторінку",
        "components.pagination.remaining-links": "І {number} інших посилань",
        "components.popUpWarning.button.cancel": "Ні, скасувати",
        "components.popUpWarning.button.confirm": "Так, підтвердити",
        "components.popUpWarning.message": "Ви впевнені, що хочете видалити це??",
        "components.popUpWarning.title": "Будь-ласка підтвердіть",
        "content-manager.App.schemas.data-loaded": "Схеми успішно завантажено",
        "content-manager.DynamicTable.relation-loaded": "Відношення завантажені",
        "content-manager.DynamicTable.relation-loading": "Відношення завантажуються",
        "content-manager.DynamicTable.relation-more": "Це відношення містить більше сутностей, ніж показано",
        "content-manager.EditRelations.title": "Реляційні дані",
        "content-manager.HeaderLayout.button.label-add-entry": "Створити новий запис",
        "content-manager.api.id": "API ID",
        "content-manager.apiError.This attribute must be unique": "{field} має бути унікальним",
        "content-manager.components.AddFilterCTA.add": "Фільтри",
        "content-manager.components.AddFilterCTA.hide": "Фільтри",
        "content-manager.components.DragHandle-label": "Перетягнути",
        "content-manager.components.DraggableAttr.edit": "Натисніть, щоб редагувати",
        "content-manager.components.DraggableCard.delete.field": "Видалити {item}",
        "content-manager.components.DraggableCard.edit.field": "Редагувати {item}",
        "content-manager.components.DraggableCard.move.field": "Переміщувати {item}",
        "content-manager.components.DynamicTable.row-line": "рядок пункту {number}",
        "content-manager.components.DynamicZone.ComponentPicker-label": "Виберати один компонент",
        "content-manager.components.DynamicZone.add-component": "Додати компонент до {componentName}",
        "content-manager.components.DynamicZone.delete-label": "Видалити {name}",
        "content-manager.components.DynamicZone.error-message": "Компонент містить помилки",
        "content-manager.components.DynamicZone.missing-components": "There {number, plural, =0 {are # missing components} one {is # missing component} other {are # missing components}}",
        "content-manager.components.DynamicZone.move-down-label": "Перемістити компонент вниз",
        "content-manager.components.DynamicZone.move-up-label": "Перемістити компонент вгору",
        "content-manager.components.DynamicZone.pick-compo": "Виберати один компонент",
        "content-manager.components.DynamicZone.required": "Потрібен компонент",
        "content-manager.components.EmptyAttributesBlock.button": "Перейдіть на сторінку налаштувань",
        "content-manager.components.EmptyAttributesBlock.description": "Ви можете змінити свої налаштування",
        "content-manager.components.FieldItem.linkToComponentLayout": "Налаштуйте макет компонента",
        "content-manager.components.FieldSelect.label": "Додати поле",
        "content-manager.components.FilterOptions.button.apply": "Застосувати",
        "content-manager.components.FiltersPickWrapper.PluginHeader.actions.apply": "Застосувати",
        "content-manager.components.FiltersPickWrapper.PluginHeader.actions.clearAll": "Очистити все",
        "content-manager.components.FiltersPickWrapper.PluginHeader.description": "Встановити умови для фільтрації записів",
        "content-manager.components.FiltersPickWrapper.PluginHeader.title.filter": "Фільтри",
        "content-manager.components.FiltersPickWrapper.hide": "Приховати",
        "content-manager.components.LeftMenu.Search.label": "Знайти тип вмісту",
        "content-manager.components.LeftMenu.collection-types": "Типи колекцій",
        "content-manager.components.LeftMenu.single-types": "Одиничні типи",
        "content-manager.components.LimitSelect.itemsPerPage": "Елементів на сторінці",
        "content-manager.components.NotAllowedInput.text": "Немає дозволів на перегляд цього поля",
        "content-manager.components.RelationInput.icon-button-aria-label": "Перетягнути",
        "content-manager.components.RepeatableComponent.error-message": "Компоненти містять помилки",
        "content-manager.components.Search.placeholder": "Пошук запису...",
        "content-manager.components.Select.draft-info-title": "Стан: Чернетка",
        "content-manager.components.Select.publish-info-title": "Стан: Опубліковано",
        "content-manager.components.SettingsViewWrapper.pluginHeader.description.edit-settings": "Налаштуйте вигляд редагування.",
        "content-manager.components.SettingsViewWrapper.pluginHeader.description.list-settings": "Визначте параметри перегляду списку.",
        "content-manager.components.SettingsViewWrapper.pluginHeader.title": "Налаштувати перегляд — {name}",
        "content-manager.components.TableDelete.delete": "Видалити все",
        "content-manager.components.TableDelete.deleteSelected": "Видалити вибране",
        "content-manager.components.TableDelete.label": "{number, plural, one {# entry} other {# entries}} вибрано",
        "content-manager.components.TableEmpty.withFilters": "Немає {contentType} із застосованими фільтрами...",
        "content-manager.components.TableEmpty.withSearch": "Немає {contentType}, що відповідає пошуковому запиту ({search})...",
        "content-manager.components.TableEmpty.withoutFilter": "Немає жодних {contentType}...",
        "content-manager.components.empty-repeatable": "Записів ще немає. Щоб додати, натисніть кнопку нижче.",
        "content-manager.components.notification.info.maximum-requirement": "Ви вже досягли максимальної кількості полів",
        "content-manager.components.notification.info.minimum-requirement": "Додано поле відповідно до мінімальних вимог",
        "content-manager.components.repeatable.reorder.error": "Під час зміни порядку полів компонента сталася помилка. Повторіть спробу",
        "content-manager.components.reset-entry": "Скинути запис",
        "content-manager.components.uid.apply": "застосувати",
        "content-manager.components.uid.available": "В наявності",
        "content-manager.components.uid.regenerate": "Згенерувати ще раз",
        "content-manager.components.uid.suggested": "запропоновано",
        "content-manager.components.uid.unavailable": "Недоступний",
        "content-manager.containers.Edit.Link.Layout": "Налаштувати макет",
        "content-manager.containers.Edit.Link.Model": "Відредагувати тип колекції",
        "content-manager.containers.Edit.addAnItem": "Додати елемент...",
        "content-manager.containers.Edit.clickToJump": "Натисніть, щоб перейти до запису",
        "content-manager.containers.Edit.delete": "Видалити",
        "content-manager.containers.Edit.delete-entry": "Видалити цей запис",
        "content-manager.containers.Edit.editing": "Редагування...",
        "content-manager.containers.Edit.information": "Інформація",
        "content-manager.containers.Edit.information.by": "за",
        "content-manager.containers.Edit.information.created": "Створено",
        "content-manager.containers.Edit.information.draftVersion": "чорновий варіант",
        "content-manager.containers.Edit.information.editing": "Редагування",
        "content-manager.containers.Edit.information.lastUpdate": "Останнє оновлення",
        "content-manager.containers.Edit.information.publishedVersion": "опублікована версія",
        "content-manager.containers.Edit.pluginHeader.title.new": "Створити запис",
        "content-manager.containers.Edit.reset": "Скинути",
        "content-manager.containers.Edit.returnList": "Повернутися до списку",
        "content-manager.containers.Edit.seeDetails": "Подробиці",
        "content-manager.containers.Edit.submit": "Зберегти",
        "content-manager.containers.EditSettingsView.modal-form.edit-field": "Відредагувати поле",
        "content-manager.containers.EditView.add.new-entry": "Додати запис",
        "content-manager.containers.EditView.notification.errors": "Форма містить деякі помилки",
        "content-manager.containers.Home.introduction": "Щоб відредагувати свої записи, перейдіть за спеціальним посиланням у меню ліворуч. Це розширення не має належного способу редагування налаштувань і все ще знаходиться в стадії активної розробки.",
        "content-manager.containers.Home.pluginHeaderDescription": "Керуйте своїми записами через потужний і красивий інтерфейс.",
        "content-manager.containers.Home.pluginHeaderTitle": "Менеджер Вмісту",
        "content-manager.containers.List.draft": "Чернетка",
        "content-manager.containers.List.errorFetchRecords": "Помилка",
        "content-manager.containers.List.published": "Опубліковано",
        "content-manager.containers.ListPage.displayedFields": "Відображені поля",
        "content-manager.containers.ListPage.items": "{number, plural, =0 {items} one {item} other {items}}",
        "content-manager.containers.ListPage.table-headers.publishedAt": "Стан",
        "content-manager.containers.ListSettingsView.modal-form.edit-label": "Редагувати {fieldName}",
        "content-manager.containers.SettingPage.add.field": "Вставити інше поле",
        "content-manager.containers.SettingPage.add.relational-field": "Вставити інше пов’язане поле",
        "content-manager.containers.SettingPage.attributes": "Поля атрибутів",
        "content-manager.containers.SettingPage.attributes.description": "Визначити порядок атрибутів",
        "content-manager.containers.SettingPage.editSettings.description": "Перетягніть поля, щоб створити макет",
        "content-manager.containers.SettingPage.editSettings.entry.title": "Заголовок запису",
        "content-manager.containers.SettingPage.editSettings.entry.title.description": "Налаштуйте відображуване поле вашого запису",
        "content-manager.containers.SettingPage.editSettings.relation-field.description": "Установіть відображуване поле як у режимі редагування, так і в режимі перегляду списку",
        "content-manager.containers.SettingPage.editSettings.title": "Редагувати вигляд (налаштування)",
        "content-manager.containers.SettingPage.layout": "Макет",
        "content-manager.containers.SettingPage.listSettings.description": "Налаштувати параметри для цього типу колекції",
        "content-manager.containers.SettingPage.listSettings.title": "Перегляд списку (налаштування)",
        "content-manager.containers.SettingPage.pluginHeaderDescription": "Налаштувати спеціальні параметри для цього типу колекції",
        "content-manager.containers.SettingPage.relations": "Пов'язані поля",
        "content-manager.containers.SettingPage.settings": "Налаштування",
        "content-manager.containers.SettingPage.view": "Вид",
        "content-manager.containers.SettingViewModel.pluginHeader.title": "Менеджер вмісту — {name}",
        "content-manager.containers.SettingsPage.Block.contentType.description": "Налаштувати конкретні параметри",
        "content-manager.containers.SettingsPage.Block.contentType.title": "Типи колекцій",
        "content-manager.containers.SettingsPage.Block.generalSettings.description": "Налаштувати параметри за замовчуванням для ваших типів колекцій",
        "content-manager.containers.SettingsPage.Block.generalSettings.title": "Загальний",
        "content-manager.containers.SettingsPage.pluginHeaderDescription": "Налаштувати параметри для всіх типів колекцій і груп",
        "content-manager.containers.SettingsView.list.subtitle": "Налаштувати макет і відображення типів колекцій і груп",
        "content-manager.containers.SettingsView.list.title": "Показати налаштування",
        "content-manager.dnd.cancel-item": "{item}, видалено. Повторне замовлення скасовано.",
        "content-manager.dnd.drop-item": "{item}, видалено. Остаточна позиція в списку: {position}.",
        "content-manager.dnd.grab-item": "{item}, захоплено. Поточна позиція в списку: {position}. Натисніть стрілку вгору та вниз, щоб змінити положення, пробіл, щоб опустити, Escape, щоб скасувати.",
        "content-manager.dnd.instructions": "Натисніть пробіл, щоб захопити та змінити порядок",
        "content-manager.dnd.reorder": "{item}, переміщено. Нова позиція в списку: {position}.",
        "content-manager.edit-settings-view.link-to-ctb.components": "Відредагувати компонент",
        "content-manager.edit-settings-view.link-to-ctb.content-types": "Відредагувати тип вмісту",
        "content-manager.emptyAttributes.button": "Перейти до конструктора типу колекції",
        "content-manager.emptyAttributes.description": "Додайте своє перше поле до типу колекції",
        "content-manager.emptyAttributes.title": "Полів ще немає",
        "content-manager.error.attribute.key.taken": "Це значення уже існує",
        "content-manager.error.attribute.sameKeyAndName": "Не можуть бути рівними",
        "content-manager.error.attribute.taken": "Ця назва поля вже існує",
        "content-manager.error.contentTypeName.taken": "Це ім'я вже існує",
        "content-manager.error.model.fetch": "Під час отримання конфігурації моделі сталася помилка.",
        "content-manager.error.record.create": "Під час створення запису сталася помилка.",
        "content-manager.error.record.delete": "Під час видалення запису сталася помилка.",
        "content-manager.error.record.fetch": "Під час отримання запису сталася помилка.",
        "content-manager.error.record.update": "Під час оновлення запису сталася помилка.",
        "content-manager.error.records.count": "Під час отримання записів підрахунку сталася помилка.",
        "content-manager.error.records.fetch": "Під час отримання записів сталася помилка.",
        "content-manager.error.schema.generation": "Під час створення схеми сталася помилка.",
        "content-manager.error.validation.json": "Це не JSON",
        "content-manager.error.validation.max": "Значення завелике.",
        "content-manager.error.validation.maxLength": "Значення задовге.",
        "content-manager.error.validation.min": "Значення занизьке.",
        "content-manager.error.validation.minLength": "Значення закоротке.",
        "content-manager.error.validation.minSupMax": "Не може бути вищим",
        "content-manager.error.validation.regex": "Значення не відповідає регулярному виразу.",
        "content-manager.error.validation.required": "Необхідно ввести це значення.",
        "content-manager.form.Input.bulkActions": "Увімкнути групові дії",
        "content-manager.form.Input.defaultSort": "Атрибут сортування за замовчуванням",
        "content-manager.form.Input.description": "Опис",
        "content-manager.form.Input.description.placeholder": "Відображати ім'я в профілі",
        "content-manager.form.Input.editable": "Поле для редагування",
        "content-manager.form.Input.filters": "Увімкнути фільтри",
        "content-manager.form.Input.hint.character.unit": "{maxValue, plural, one { character} other { characters}}",
        "content-manager.form.Input.hint.minMaxDivider": " / ",
        "content-manager.form.Input.hint.text": "{min, select, undefined {} other {min. {min}}}{divider}{max, select, undefined {} other {max. {max}}}{unit}{br}{description}",
        "content-manager.form.Input.label": "Ярлик",
        "content-manager.form.Input.label.inputDescription": "Це значення перекриває ярлик, що відображається в заголовку таблиці",
        "content-manager.form.Input.pageEntries": "Записів на сторінці",
        "content-manager.form.Input.pageEntries.inputDescription": "Примітка. Ви можете змінити це значення на сторінці налаштувань типу колекції.",
        "content-manager.form.Input.placeholder": "Заповнювач",
        "content-manager.form.Input.placeholder.placeholder": "Моє чудове значення",
        "content-manager.form.Input.search": "Увімкнути пошук",
        "content-manager.form.Input.search.field": "Увімкнути пошук в цьому полі",
        "content-manager.form.Input.sort.field": "Увімкнути сортування в цьому полі",
        "content-manager.form.Input.sort.order": "Порядок сортування за замовчуванням",
        "content-manager.form.Input.wysiwyg": "Відображати як WYSIWYG",
        "content-manager.global.displayedFields": "Відображені поля",
        "content-manager.groups": "Групи",
        "content-manager.groups.numbered": "Групи ({number})",
        "content-manager.header.name": "Вміст",
        "content-manager.link-to-ctb": "Відредагувати модель",
        "content-manager.models": "Типи колекцій",
        "content-manager.models.numbered": "Типи колекцій ({number})",
        "content-manager.notification.error.displayedFields": "Потрібно принаймні одне відображене поле",
        "content-manager.notification.error.relationship.fetch": "Сталася помилка під час отримання зв’язку.",
        "content-manager.notification.info.SettingPage.disableSort": "Потрібно мати один атрибут із дозволеним сортуванням",
        "content-manager.notification.info.minimumFields": "Ви повинні мати принаймні одне поле",
        "content-manager.notification.upload.error": "Під час завантаження ваших файлів сталася помилка",
        "content-manager.pageNotFound": "Сторінку не знайдено",
        "content-manager.pages.ListView.header-subtitle": "{number, plural, =0 {# entries} one {# entry} other {# entries}} знайдено",
        "content-manager.pages.NoContentType.button": "Створіть свій перший тип вмісту",
        "content-manager.pages.NoContentType.text": "У вас ще немає вмісту, рекомендуємо вам створити свій перший тип вмісту.",
        "content-manager.permissions.not-allowed.create": "Вам заборонено створювати документ",
        "content-manager.permissions.not-allowed.update": "Вам заборонено переглядати цей документ",
        "content-manager.plugin.description.long": "Швидкий спосіб перегляду, редагування та видалення даних у вашій базі даних.",
        "content-manager.plugin.description.short": "Швидкий спосіб перегляду, редагування та видалення даних у вашій базі даних.",
        "content-manager.popUpWarning.bodyMessage.contentType.delete": "Ви впевнені, що хочете видалити тип вмісту?",
        "content-manager.popUpWarning.bodyMessage.contentType.delete.all": "Ви впевнені, що хочете видалити всі типи вмісту?",
        "content-manager.popUpWarning.warning.has-draft-relations.title": "Підтвердження",
        "content-manager.popUpWarning.warning.publish-question": "Ви все ще хочете опублікувати?",
        "content-manager.popUpWarning.warning.unpublish": "Якщо ви не опублікуєте цей вміст, він автоматично перетвориться на чернетку.",
        "content-manager.popUpWarning.warning.unpublish-question": "Ви впевнені, що не хочете це публікувати?",
        "content-manager.popUpWarning.warning.updateAllSettings": "Це змінить усі ваші налаштування",
        "content-manager.popUpwarning.warning.has-draft-relations.button-confirm": "Так, опублікувати",
        "content-manager.popUpwarning.warning.has-draft-relations.message": "<b>{count, plural, one { відношення є } other { відношення є } }</b> ще не опубліковано та може призвести до неочікуваної поведінки.",
        "content-manager.popover.display-relations.label": "Показати в",
        "content-manager.relation.add": "Додайте відношення",
        "content-manager.relation.disconnect": "Видалити",
        "content-manager.relation.isLoading": "Відношення завантажуються",
        "content-manager.relation.loadMore": "Завантажити ще",
        "content-manager.relation.notAvailable": "Відношення відсутні",
        "content-manager.relation.publicationState.draft": "Чернетка",
        "content-manager.relation.publicationState.published": "Опубліковано",
        "content-manager.reviewWorkflows.stage.label": "Етап огляду",
        "content-manager.select.currently.selected": "{count} зараз вибрано",
        "content-manager.success.record.delete": "Видалено",
        "content-manager.success.record.publish": "Опубліковано",
        "content-manager.success.record.save": "Збережено",
        "content-manager.success.record.unpublish": "Неопубліковано",
        "content-manager.utils.data-loaded": "{number, plural, =1 {entry has} other {entries have}} успішно завантажено",
        "dark": "Темний",
        "form.button.continue": "Продовжити",
        "form.button.done": "Готово",
        "global.actions": "Дії",
        "global.auditLogs": "Журнали аудиту",
        "global.back": "Назад",
        "global.cancel": "Скасувати",
        "global.change-password": "Змінити пароль",
        "global.content-manager": "Менеджер Вмісту",
        "global.continue": "Продовжити",
        "global.delete": "Видалити",
        "global.delete-target": "Видалити {target}",
        "global.description": "Опис",
        "global.details": "Подробиці",
        "global.disabled": "Вимкнено",
        "global.documentation": "Документація",
        "global.enabled": "Увімкнено",
        "global.finish": "Закінчити",
        "global.marketplace": "Маркетплейс",
        "global.name": "Ім'я",
        "global.none": "Жодного",
        "global.password": "Пароль",
        "global.plugins": "Розширення",
        "global.plugins.content-manager": "Менеджер Вмісту",
        "global.plugins.content-manager.description": "Швидкий спосіб перегляду, редагування та видалення даних у вашій базі даних.",
        "global.plugins.content-type-builder": "Конструктор типів вмісту",
        "global.plugins.content-type-builder.description": "Змоделюйте структуру даних вашого API. Створіть нові поля та відношення всього за хвилину. Файли автоматично створюються та оновлюються у вашому проекті.",
        "global.plugins.documentation": "Документація",
        "global.plugins.documentation.description": "Створіть документ OpenAPI та візуалізуйте свій API за допомогою SWAGGER UI.",
        "global.plugins.email": "Email",
        "global.plugins.email.description": "Налаштуйте програму для надсилання електронних листів.",
        "global.plugins.graphql": "GraphQL",
        "global.plugins.graphql.description": "Додати кінцеву точку GraphQL із стандартними методами API.",
        "global.plugins.i18n": "Інтернаціоналізація",
        "global.plugins.i18n.description": "Цей плагін дозволяє створювати, читати та оновлювати вміст різними мовами як з панелі адміністратора, так і з API.",
        "global.plugins.sentry": "Sentry",
        "global.plugins.sentry.description": "Надсилати події помилок Strapi до Sentry.",
        "global.plugins.upload": "Медіатека",
        "global.plugins.upload.description": "Керування медіафайлами.",
        "global.plugins.users-permissions": "Ролі та дозволи",
        "global.plugins.users-permissions.description": "Захистіть свій API за допомогою процесу повної автентифікації на основі JWT. Цей плагін також постачається зі стратегією ACL, яка дозволяє вам керувати дозволами між групами користувачів.",
        "global.profile": "Профіль",
        "global.prompt.unsaved": "Ви впевнені, що бажаєте залишити цю сторінку? Усі ваші зміни буде втрачено",
        "global.reset-password": "Скинути пароль",
        "global.roles": "Ролі",
        "global.save": "Зберегти",
        "global.search": "Пошук",
        "global.see-more": "Побачити більше",
        "global.select": "Виберіть",
        "global.select-all-entries": "Виберіть усі записи",
        "global.settings": "Налаштування",
        "global.type": "Тип",
        "global.users": "Користувачі",
        "light": "Світлий",
        "notification.contentType.relations.conflict": "Тип вмісту має конфліктні відношення",
        "notification.default.title": "Інформація:",
        "notification.ee.warning.at-seat-limit.title": "{licenseLimitStatus, select, OVER_LIMIT {Over} AT_LIMIT {At}} обмеження кількості місць ({currentUserCount}/{permittedSeats})",
        "notification.ee.warning.over-.message": "Додайте місця до {licenseLimitStatus, select, OVER_LIMIT {invite} AT_LIMIT {re-enable}} Users. Якщо ви вже це зробили, але це ще не відображено в Strapi, обов’язково перезапустіть програму.",
        "notification.error": "Виникла помилка",
        "notification.error.invalid.configuration": "У вас неправильна конфігурація, перевірте журнал свого сервера для отримання додаткової інформації.",
        "notification.error.layout": "Не вдалося отримати макет",
        "notification.error.tokennamenotunique": "Ім’я вже призначено іншому токену",
        "notification.form.error.fields": "Форма містить деякі помилки",
        "notification.form.success.fields": "Зміни збережено",
        "notification.link-copied": "Посилання скопійовано в буфер обміну",
        "notification.permission.not-allowed-read": "Вам заборонено переглядати цей документ",
        "notification.success.apitokencreated": "Токен API успішно створено",
        "notification.success.apitokenedited": "API токен успішно відредаговано",
        "notification.success.delete": "Елемент видалено",
        "notification.success.saved": "Збережено",
        "notification.success.title": "Успіх:",
        "notification.success.transfertokencreated": "Токен передачі успішно створено",
        "notification.success.transfertokenedited": "Токен передачі успішно відредаговано",
        "notification.version.update.message": "Доступна нова версія Strapi!",
        "notification.warning.404": "404 - Не знайдено",
        "notification.warning.title": "Увага:",
        "or": "АБО",
        "request.error.model.unknown": "Цієї моделі не існує",
        "selectButtonTitle": "Виберіть",
        "skipToContent": "Перейти до вмісту",
        "submit": "Надіслати"
      }
      
    }
  },
  bootstrap(app) {
    console.log(app);
  },
};
