export default {
  config: {
    locales: [
      // 'ar',
      // 'fr',
      // 'cs',
      // 'de',
      // 'dk',
      // 'es',
      // 'he',
      // 'id',
      // 'it',
      // 'ja',
      // 'ko',
      // 'ms',
      // 'nl',
      // 'no',
      // 'pl',
      // 'pt-BR',
      // 'pt',
      // 'ru',
      // 'sk',
      // 'sv',
      // 'th',
      // 'tr',
      'uk',
      // 'vi',
      // 'zh-Hans',
      // 'zh',
    ],
    translations: {
      'uk' : {
        "Analytics": "Аналітика",
        "Auth.components.Oops.text": "Ваш обліковий запис призупинено.",
        "Auth.components.Oops.text.admin": "Якщо це помилка, зверніться до адміністратора.",
        "Auth.components.Oops.title": "Ой...",
        "Auth.form.active.label": "Активний",
        "Auth.form.button.forgot-password": "Відправити email",
        "Auth.form.button.go-home": "ПОВЕРНУТИСЯ ДОДОМУ",
        "Auth.form.button.login": "Логін",
        "Auth.form.button.login.providers.error": "Ми не можемо підключити вас через вибраного провайдера.",
        "Auth.form.button.login.strapi": "Увійдіть через Strapi",
        "Auth.form.button.password-recovery": "Відновлення паролю",
        "Auth.form.button.register": "Давайте розпочнемо",
        "Auth.form.confirmPassword.label": "Підтвердьте пароль",
        "Auth.form.currentPassword.label": "Поточний пароль",
        "Auth.form.email.label": "Email",
        "Auth.form.email.placeholder": "напр. kai@doe.com",
        "Auth.form.error.blocked": "Ваш обліковий запис заблоковано адміністратором.",
        "Auth.form.error.code.provide": "Надано неправильний код.",
        "Auth.form.error.confirmed": "Email вашого облікового запису не підтверджена.",
        "Auth.form.error.email.invalid": "Цей email недійсний.",
        "Auth.form.error.email.provide": "Будь ласка, вкажіть своє ім'я користувача або свій email.",
        "Auth.form.error.email.taken": "Email вже зайнятий.",
        "Auth.form.error.invalid": "Недійсний ідентифікатор або пароль.",
        "Auth.form.error.params.provide": "Надано неправильні параметри.",
        "Auth.form.error.password.format": "Ваш пароль не може містити символ `$` більше трьох разів.",
        "Auth.form.error.password.local": "Цей користувач ніколи не встановлював локальний пароль, увійдіть через провайдера, який використовувався під час створення облікового запису.",
        "Auth.form.error.password.matching": "Паролі не співпадають.",
        "Auth.form.error.password.provide": "Будь ласка, введіть свій пароль.",
        "Auth.form.error.ratelimit": "Забагато спроб. Повторіть спробу через хвилину.",
        "Auth.form.error.user.not-exist": "Цього email не існує.",
        "Auth.form.error.username.taken": "Таке ім'я вже використовується.",
        "Auth.form.firstname.label": "Ім'я",
        "Auth.form.firstname.placeholder": "напр. Олег",
        "Auth.form.forgot-password.email.label": "Введіть ваш email",
        "Auth.form.forgot-password.email.label.success": "Email успішно надіслано",
        "Auth.form.lastname.label": "Прізвище",
        "Auth.form.lastname.placeholder": "напр. Петренко",
        "Auth.form.password.hide-password": "Приховати пароль",
        "Auth.form.password.hint": "Має бути принаймні 8 символів, 1 велика, 1 нижня та 1 цифра",
        "Auth.form.password.show-password": "Показати пароль",
        "Auth.form.register.news.label": "Повідомляти мені про нові функції та майбутні вдосконалення (цим ви приймаєте {terms} і {policy}).",
        "Auth.form.register.subtitle": "Облікові дані використовуються лише для автентифікації в Strapi. Усі збережені дані будуть зберігатися у вашій базі даних.",
        "Auth.form.rememberMe.label": "Запам'ятати мене",
        "Auth.form.username.label": "Ім'я користувача",
        "Auth.form.username.placeholder": "напр. Олег_Петренко",
        "Auth.form.welcome.subtitle": "Увійдіть у свій обліковий запис Strapi",
        "Auth.form.welcome.title": "Ласкаво просимо до Strapi!",
        "Auth.link.forgot-password": "Забули свій пароль?",
        "Auth.link.ready": "Готові до входу?",
        "Auth.link.signin": "Увійти",
        "Auth.link.signin.account": "Вже маєте аккаунт?",
        "Auth.login.sso.divider": "Або увійдіти за допомогою",
        "Auth.login.sso.loading": "Завантаження провайдерів...",
        "Auth.login.sso.subtitle": "Увійдіть у свій обліковий запис через SSO",
        "Auth.privacy-policy-agreement.policy": "політика конфіденційності",
        "Auth.privacy-policy-agreement.terms": "умови",
        "Auth.reset-password.title": "Скинути пароль",
        "Content Manager": "Менеджер Вмісту",
        "Content Type Builder": "Конструктор Типів Вмісту",
        "Documentation": "Документація",
        "Email": "Email",
        "Files Upload": "Завантаження файлів",
        "HomePage.helmet.title": "Домашня сторінка",
        "HomePage.roadmap": "Перегляньте нашу дорожню карту",
        "HomePage.welcome.congrats": "Вітаємо!",
        "HomePage.welcome.congrats.content": "Ви ввійшли як перший адміністратор. Щоб дізнатися про потужні функції Strapi,",
        "HomePage.welcome.congrats.content.bold": "ми рекомендуємо вам створити свій перший тип колекції.",
        "Media Library": "Медіатека",
        "New entry": "Новий запис",
        "Password": "Пароль",
        "Provider": "Провайдер",
        "ResetPasswordToken": "Скинути токен пароля",
        "Role": "Роль",
        "Roles & Permissions": "Ролі та Дозволи",
        "Roles.ListPage.notification.delete-all-not-allowed": "Деякі ролі не вдалося видалити, оскільки вони пов’язані з користувачами",
        "Roles.ListPage.notification.delete-not-allowed": "Роль не можна видалити, якщо вона пов’язана з користувачами",
        "Roles.RoleRow.select-all": "Виберіть {name} для групових дій",
        "Roles.RoleRow.user-count": "{number, plural, =0 {# user} one {# user} other {# users}}",
        "Roles.components.List.empty.withSearch": "Немає ролі, що відповідає пошуку ({search})...",
        "Settings.PageTitle": "Налаштування — {name}",
        "Settings.apiTokens.ListView.headers.createdAt": "Створено в",
        "Settings.apiTokens.ListView.headers.description": "Опис",
        "Settings.apiTokens.ListView.headers.lastUsedAt": "Останнє використання",
        "Settings.apiTokens.ListView.headers.name": "Ім'я",
        "Settings.apiTokens.ListView.headers.type": "Тип токену",
        "Settings.apiTokens.addFirstToken": "Додайте свій перший токен API",
        "Settings.apiTokens.addNewToken": "Додати новий API токен",
        "Settings.apiTokens.create": "Створити новий API токен",
        "Settings.apiTokens.createPage.BoundRoute.title": "Маршрут до",
        "Settings.apiTokens.createPage.permissions.description": "Нижче наведено лише дії, пов’язані з маршрутом.",
        "Settings.apiTokens.createPage.permissions.header.hint": "Виберіть дії програми або дії плагіна та клацніть піктограму шестерінки, щоб відобразити прив’язаний маршрут",
        "Settings.apiTokens.createPage.permissions.header.title": "Розширені налаштування",
        "Settings.apiTokens.createPage.permissions.title": "Дозволи",
        "Settings.apiTokens.createPage.title": "Створити токен API",
        "Settings.apiTokens.description": "Список згенерованих токенів для використання API",
        "Settings.apiTokens.emptyStateLayout": "У вас ще немає вмісту...",
        "Settings.apiTokens.regenerate": "Згенерувати заново",
        "Settings.apiTokens.title": "API токени",
        "Settings.application.customization": "Кастомізація",
        "Settings.application.customization.auth-logo.carousel-hint": "Замініть логотип на сторінках автентифікації",
        "Settings.application.customization.carousel-hint": "Змінити логотип панелі адміністратора (максимальний розмір: {dimension}x{dimension}, максимальний розмір файлу: {size}KB)",
        "Settings.application.customization.carousel-slide.label": "Логотип слайд",
        "Settings.application.customization.carousel.auth-logo.title": "Логотип Auth",
        "Settings.application.customization.carousel.change-action": "Змінити логотип",
        "Settings.application.customization.carousel.menu-logo.title": "Логотип меню",
        "Settings.application.customization.carousel.reset-action": "Скинути логотип",
        "Settings.application.customization.carousel.title": "Логотип",
        "Settings.application.customization.menu-logo.carousel-hint": "Замінити логотип у головній навігації",
        "Settings.application.customization.modal.cancel": "Скасувати",
        "Settings.application.customization.modal.pending": "Логотип очікує на розгляд",
        "Settings.application.customization.modal.pending.card-badge": "зображення",
        "Settings.application.customization.modal.pending.choose-another": "Виберіть інший логотип",
        "Settings.application.customization.modal.pending.subtitle": "Керуйте вибраним логотипом перед його завантаженням",
        "Settings.application.customization.modal.pending.title": "Логотип готовий до завантаження",
        "Settings.application.customization.modal.pending.upload": "Завантажити логотип",
        "Settings.application.customization.modal.tab.label": "Як ви хочете завантажити свої ресурси?",
        "Settings.application.customization.modal.upload": "Завантажити логотип",
        "Settings.application.customization.modal.upload.cta.browse": "Перегляд файлів",
        "Settings.application.customization.modal.upload.drag-drop": "Перетягніть сюди або",
        "Settings.application.customization.modal.upload.error-format": "Завантажено неправильний формат (підтримуються лише формати: jpeg, jpg, png, svg).",
        "Settings.application.customization.modal.upload.error-network": "Помилка мережі",
        "Settings.application.customization.modal.upload.error-size": "Завантажений файл завеликий (максимальний розмір: {dimension}x{dimension}, максимальний розмір файлу: {size}KB)",
        "Settings.application.customization.modal.upload.file-validation": "Максимальний розмір: {dimension}x{dimension}, максимальний розмір: {size}KB",
        "Settings.application.customization.modal.upload.from-computer": "З комп'ютера",
        "Settings.application.customization.modal.upload.from-url": "З URL",
        "Settings.application.customization.modal.upload.from-url.input-label": "URL",
        "Settings.application.customization.modal.upload.next": "Далі",
        "Settings.application.customization.size-details": "Максимальний розмір: {dimension}×{dimension}, максимальний розмір файлу: {size}KB",
        "Settings.application.description": "Глобальна інформація адміністративної панелі",
        "Settings.application.edition-title": "поточний план",
        "Settings.application.ee-or-ce": "{communityEdition, select, true {Community Edition} other {Enterprise Edition}}",
        "Settings.application.ee.admin-seats.add-seats": "{isHostedOnStrapiCloud, select, true {Add seats} other {Contact sales}}",
        "Settings.application.ee.admin-seats.at-limit-tooltip": "На межі: додайте місця, щоб запросити більше користувачів",
        "Settings.application.ee.admin-seats.count": "<text>{enforcementUserCount}</text>/{permittedSeats}",
        "Settings.application.get-help": "Отримати допомогу",
        "Settings.application.link-pricing": "Переглянути всі тарифні плани",
        "Settings.application.link-upgrade": "Оновіть панель адміністратора",
        "Settings.application.node-version": "node версія",
        "Settings.application.strapi-version": "Strapi версія",
        "Settings.application.strapiVersion": "Strapi версія",
        "Settings.application.title": "Огляд",
        "Settings.error": "Помилка",
        "Settings.global": "Глобальні налаштування",
        "Settings.permissions": "Панель адміністрування",
        "Settings.permissions.auditLogs.action": "Дія",
        "Settings.permissions.auditLogs.admin.auth.success": "Логін адміністратора",
        "Settings.permissions.auditLogs.admin.logout": "Вихід адміністратора",
        "Settings.permissions.auditLogs.component.create": "Створити компонент",
        "Settings.permissions.auditLogs.component.delete": "Видалити компонент",
        "Settings.permissions.auditLogs.component.update": "Оновити компонент",
        "Settings.permissions.auditLogs.content-type.create": "Створення типу вмісту",
        "Settings.permissions.auditLogs.content-type.delete": "Видалити тип вмісту",
        "Settings.permissions.auditLogs.content-type.update": "Оновити тип вмісту",
        "Settings.permissions.auditLogs.date": "Дата",
        "Settings.permissions.auditLogs.details": "Деталі журналу",
        "Settings.permissions.auditLogs.entry.create": "Створити запис{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.entry.delete": "Видалити запис{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.entry.publish": "Опублікувати запис {model, select, undefined {} other {({model})}}",
        "Settings.permissions.auditLogs.entry.unpublish": "Скасувати публікацію запису{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.entry.update": "Оновити запис{model, select, undefined {} other { ({model})}}",
        "Settings.permissions.auditLogs.filters.combobox.aria-label": "Знайдіть і виберіть параметр для фільтрування",
        "Settings.permissions.auditLogs.listview.header.subtitle": "Журнали всіх дій, які відбувалися у вашому оточенні",
        "Settings.permissions.auditLogs.media.create": "Створити медіа",
        "Settings.permissions.auditLogs.media.delete": "Видалити медіа",
        "Settings.permissions.auditLogs.media.update": "Оновити медіа",
        "Settings.permissions.auditLogs.payload": "Корисне навантаження",
        "Settings.permissions.auditLogs.permission.create": "Створити дозвіл",
        "Settings.permissions.auditLogs.permission.delete": "Видалити дозвіл",
        "Settings.permissions.auditLogs.permission.update": "Оновити дозвіл",
        "Settings.permissions.auditLogs.role.create": "Створити роль",
        "Settings.permissions.auditLogs.role.delete": "Видалити роль",
        "Settings.permissions.auditLogs.role.update": "Оновити роль",
        "Settings.permissions.auditLogs.user": "Користувач",
        "Settings.permissions.auditLogs.user.create": "Створити користувача",
        "Settings.permissions.auditLogs.user.delete": "Видалити користувача",
        "Settings.permissions.auditLogs.user.fullname": "{firstname} {lastname}",
        "Settings.permissions.auditLogs.user.update": "Оновити користувача",
        "Settings.permissions.auditLogs.userId": "Ідентифікатор користувача",
        "Settings.permissions.category": "Налаштування дозволів для {category}",
        "Settings.permissions.category.plugins": "Налаштування дозволів для розширення {category}",
        "Settings.permissions.conditions.anytime": "Будь-коли",
        "Settings.permissions.conditions.apply": "Застосувати",
        "Settings.permissions.conditions.can": "Може",
        "Settings.permissions.conditions.conditions": "Умови",
        "Settings.permissions.conditions.define-conditions": "Визначити умови",
        "Settings.permissions.conditions.links": "Посилання",
        "Settings.permissions.conditions.no-actions": "Спочатку вам потрібно вибрати дії (створити, прочитати, оновити, ...), перш ніж визначати умови для них.",
        "Settings.permissions.conditions.none-selected": "Будь-коли",
        "Settings.permissions.conditions.or": "АБО",
        "Settings.permissions.conditions.when": "Коли",
        "Settings.permissions.select-all-by-permission": "Виберіть усі дозволи {label}",
        "Settings.permissions.select-by-permission": "Виберіть дозвіл {label}",
        "Settings.permissions.users.active": "Активний",
        "Settings.permissions.users.create": "Запросити нового користувача",
        "Settings.permissions.users.email": "Email",
        "Settings.permissions.users.firstname": "Ім'я",
        "Settings.permissions.users.form.sso": "Підключитися через SSO",
        "Settings.permissions.users.form.sso.description": "Якщо ввімкнено (ON), користувачі можуть входити через SSO",
        "Settings.permissions.users.inactive": "Неактивний",
        "Settings.permissions.users.lastname": "Прізвище",
        "Settings.permissions.users.listview.header.subtitle": "Усі користувачі, які мають доступ до панелі адміністратора Strapi",
        "Settings.permissions.users.roles": "Ролі",
        "Settings.permissions.users.strapi-author": "Автор",
        "Settings.permissions.users.strapi-editor": "Редактор",
        "Settings.permissions.users.strapi-super-admin": "Супер адміністратор",
        "Settings.permissions.users.tabs.label": "Вкладки Дозволи",
        "Settings.permissions.users.user-status": "Статус користувача",
        "Settings.permissions.users.username": "Ім'я користувача",
        "Settings.profile.form.notify.data.loaded": "Дані вашого профілю завантажено",
        "Settings.profile.form.section.experience.clear.select": "Очистіть вибрану мову інтерфейсу",
        "Settings.profile.form.section.experience.here": "тут",
        "Settings.profile.form.section.experience.interfaceLanguage": "Мова інтерфейсу",
        "Settings.profile.form.section.experience.interfaceLanguage.hint": "Це відображатиме лише ваш власний інтерфейс вибраною мовою.",
        "Settings.profile.form.section.experience.interfaceLanguageHelp": "Зміни налаштувань стосуватимуться лише вас. Більше інформації доступно {тут}.",
        "Settings.profile.form.section.experience.mode.hint": "Відображає ваш інтерфейс у вибраному режимі.",
        "Settings.profile.form.section.experience.mode.label": "Режим інтерфейсу",
        "Settings.profile.form.section.experience.mode.option-label": "Режим {name}",
        "Settings.profile.form.section.experience.title": "Досвід",
        "Settings.profile.form.section.helmet.title": "Профіль користувача",
        "Settings.profile.form.section.profile.page.title": "Сторінка профілю",
        "Settings.review-workflows.page.title": "Перегляд робочих процесів",
        "Settings.review-workflows.page.subtitle": "{count, plural, one {# stage} other {# stages}}",
        "Settings.review-workflows.page.isLoading": "Робочий процес завантажується",
        "Settings.review-workflows.page.delete.confirm.body": "Усі записи, призначені видаленим етапам, буде перенесено на попередній етап. Ви впевнені, що хочете зберегти?",
        "Settings.review-workflows.stage.name.label": "Назва етапу",
        "Settings.roles.create.description": "Визначте права, надані ролі",
        "Settings.roles.create.title": "Створіть роль",
        "Settings.roles.created": "Роль створено",
        "Settings.roles.edit.title": "Редагувати роль",
        "Settings.roles.form.button.users-with-role": "{number, plural, =0 {# users} one {# user} other {# users}} з цією роллю",
        "Settings.roles.form.created": "Створено",
        "Settings.roles.form.description": "Назва та опис ролі",
        "Settings.roles.form.permission.property-label": "{label} дозволи",
        "Settings.roles.form.permissions.attributesPermissions": "Дозволи полів",
        "Settings.roles.form.permissions.create": "Створити",
        "Settings.roles.form.permissions.delete": "Видалити",
        "Settings.roles.form.permissions.publish": "Опублікувати",
        "Settings.roles.form.permissions.read": "Читати",
        "Settings.roles.form.permissions.update": "Оновити",
        "Settings.roles.list.button.add": "Додати нову роль",
        "Settings.roles.list.description": "Список ролей",
        "Settings.roles.title.singular": "роль",
        "Settings.sso.description": "Налаштуйте параметри функції єдиного входу.",
        "Settings.sso.form.defaultRole.description": "Це приєднає нового автентифікованого користувача до вибраної ролі",
        "Settings.sso.form.defaultRole.description-not-allowed": "Щоб читати ролі адміністратора, потрібно мати дозвіл",
        "Settings.sso.form.defaultRole.label": "Роль за замовчуванням",
        "Settings.sso.form.registration.description": "Створіть нового користувача для входу в систему SSO, якщо обліковий запис не існує",
        "Settings.sso.form.registration.label": "Автоматична реєстрація",
        "Settings.sso.title": "Єдиний вхід",
        "Settings.tokens.Button.cancel": "Скасувати",
        "Settings.tokens.Button.regenerate": "Створити заново",
        "Settings.tokens.ListView.headers.createdAt": "Створено в",
        "Settings.tokens.ListView.headers.description": "Опис",
        "Settings.tokens.ListView.headers.lastUsedAt": "Востаннє використано",
        "Settings.tokens.ListView.headers.name": "Ім'я",
        "Settings.tokens.RegenerateDialog.title": "Створити токен заново",
        "Settings.tokens.copy.editMessage": "З міркувань безпеки ви можете побачити свій токен лише один раз.",
        "Settings.tokens.copy.editTitle": "Цей токен більше не доступний.",
        "Settings.tokens.copy.lastWarning": "Обов’язково скопіюйте цей токен, ви більше не зможете його побачити!",
        "Settings.tokens.duration.30-days": "30 днів",
        "Settings.tokens.duration.7-days": "7 днів",
        "Settings.tokens.duration.90-days": "90 днів",
        "Settings.tokens.duration.expiration-date": "Термін придатності",
        "Settings.tokens.duration.unlimited": "Необмежений",
        "Settings.tokens.form.description": "Опис",
        "Settings.tokens.form.duration": "Тривалість токена",
        "Settings.tokens.form.name": "Ім'я",
        "Settings.tokens.form.type": "Тип токена",
        "Settings.tokens.notification.copied": "Токен скопійовано в буфер обміну.",
        "Settings.tokens.popUpWarning.message": "Ви впевнені, що бажаєте створити заново цей токен?",
        "Settings.tokens.regenerate": "Створити заново",
        "Settings.tokens.types.custom": "Кастомний",
        "Settings.tokens.types.full-access": "Повний доступ",
        "Settings.tokens.types.read-only": "Лише для читання",
        "Settings.transferTokens.ListView.headers.type": "Тип токена",
        "Settings.transferTokens.addFirstToken": "Додайте свій перший токен передачі",
        "Settings.transferTokens.addNewToken": "Додайте новий токен передачі",
        "Settings.transferTokens.create": "Створіть новий токен передачі",
        "Settings.transferTokens.createPage.title": "Створіть токен передачі",
        "Settings.transferTokens.description": "Список згенерованих токенів передачі",
        "Settings.transferTokens.emptyStateLayout": "У вас ще немає вмісту...",
        "Settings.transferTokens.title": "Токени передачі",
        "Settings.webhooks.create": "Створіть вебхук",
        "Settings.webhooks.create.header": "Створити новий заголовок",
        "Settings.webhooks.created": "Вебхук створено",
        "Settings.webhooks.event.publish-tooltip": "Ця подія існує лише для вмісту з увімкненою системою Draft/Publish",
        "Settings.webhooks.events.create": "Створити",
        "Settings.webhooks.events.update": "Оновити",
        "Settings.webhooks.form.events": "Події",
        "Settings.webhooks.form.headers": "Заголовки",
        "Settings.webhooks.form.url": "URL",
        "Settings.webhooks.headers.remove": "Видалити рядок заголовка {number}",
        "Settings.webhooks.key": "Ключ",
        "Settings.webhooks.list.button.add": "Створити новий вебхук",
        "Settings.webhooks.list.description": "Отримувати сповіщення про зміни POST",
        "Settings.webhooks.list.empty.description": "Вебхуки не знайдено",
        "Settings.webhooks.list.empty.link": "Перегляньте нашу документацію",
        "Settings.webhooks.list.empty.title": "Вебхуків ще немає",
        "Settings.webhooks.list.th.actions": "дії",
        "Settings.webhooks.list.th.status": "статус",
        "Settings.webhooks.singular": "вебхук",
        "Settings.webhooks.title": "Веб-хуки",
        "Settings.webhooks.to.delete": "{webhooksToDeleteLength, plural, one {# asset} other {# assets}} вибрано",
        "Settings.webhooks.trigger": "Тригер",
        "Settings.webhooks.trigger.cancel": "Скасувати тригер",
        "Settings.webhooks.trigger.pending": "В очікуванні…",
        "Settings.webhooks.trigger.save": "Будь ласка, збережіть для запуску",
        "Settings.webhooks.trigger.success": "Успіх!",
        "Settings.webhooks.trigger.success.label": "Тригер вдався",
        "Settings.webhooks.trigger.test": "Тест-тригер",
        "Settings.webhooks.trigger.title": "Зберегти перед запуском",
        "Settings.webhooks.value": "Значення",
        "Usecase.back-end": "Back-end розробник",
        "Usecase.button.skip": "Пропустити це запитання",
        "Usecase.content-creator": "Творець вмісту",
        "Usecase.front-end": "Front-end розробник",
        "Usecase.full-stack": "Full-stack розробник",
        "Usecase.input.work-type": "Який вид роботи ви виконуєте?",
        "Usecase.notification.success.project-created": "Проект успішно створено",
        "Usecase.other": "Інше",
        "Usecase.title": "Розкажіть нам трохи більше про себе",
        "Username": "Ім'я користувача",
        "Users & Permissions": "Користувачі та дозволи",
        "Users": "Користувачі",
        "Users.components.List.empty": "Користувачів немає...",
        "Users.components.List.empty.withFilters": "Немає користувачів із застосованими фільтрами...",
        "Users.components.List.empty.withSearch": "Немає користувачів, які відповідають запиту ({search})...",
        "admin.pages.MarketPlacePage.filters.categories": "Категорії",
        "admin.pages.MarketPlacePage.filters.categoriesSelected": "{count, plural, =0 {No categories} one {# category} other {# categories}} вибрано",
        "admin.pages.MarketPlacePage.filters.collections": "Колекції",
        "admin.pages.MarketPlacePage.filters.collectionsSelected": "{count, plural, =0 {No Collections} one {# Collection} other {# Collections}} вибрано",
        "admin.pages.MarketPlacePage.helmet": "Маркетплейс - Розширення",
        "admin.pages.MarketPlacePage.missingPlugin.description": "Скажіть нам, яке розширення ви шукаєте, і ми повідомимо розробників розширень нашої спільноти, якщо вони шукатимуть натхнення!",
        "admin.pages.MarketPlacePage.missingPlugin.title": "Відсутнє розширення?",
        "admin.pages.MarketPlacePage.offline.subtitle": "Щоб отримати доступ до Strapi Market, потрібно підключитися до Інтернету.",
        "admin.pages.MarketPlacePage.offline.title": "Ви в режимі офлайн",
        "admin.pages.MarketPlacePage.plugin.copy": "Копіювати команду встановлення",
        "admin.pages.MarketPlacePage.plugin.copy.success": "Команда встановлення готова до вставлення у ваш термінал",
        "admin.pages.MarketPlacePage.plugin.downloads": "Це розширення має {downloadsCount} щотижневих завантажень",
        "admin.pages.MarketPlacePage.plugin.githubStars": "Це розширення позначено зірочкою {starsCount} разів на GitHub",
        "admin.pages.MarketPlacePage.plugin.info": "Дізнатись більше",
        "admin.pages.MarketPlacePage.plugin.info.label": "Дізнатись більше про {pluginName}",
        "admin.pages.MarketPlacePage.plugin.info.text": "Більше",
        "admin.pages.MarketPlacePage.plugin.installed": "Встановлено",
        "admin.pages.MarketPlacePage.plugin.tooltip.madeByStrapi": "Зроблено Strapi",
        "admin.pages.MarketPlacePage.plugin.tooltip.verified": "Розширення перевірено Strapi",
        "admin.pages.MarketPlacePage.plugin.version": "Оновіть свою версію Strapi: \"{strapiAppVersion}\" до: \"{versionRange}\"",
        "admin.pages.MarketPlacePage.plugin.version.null": "Не вдалося перевірити сумісність із вашою версією Strapi: \"{strapiAppVersion}\"",
        "admin.pages.MarketPlacePage.plugins": "Розширення",
        "admin.pages.MarketPlacePage.provider.downloads": "Цей провайдер має {downloadsCount} щотижневих завантажень",
        "admin.pages.MarketPlacePage.provider.githubStars": "Цей провайдер позначено зірочкою {starsCount} на GitHub",
        "admin.pages.MarketPlacePage.providers": "Провайдери",
        "admin.pages.MarketPlacePage.search.clear": "Очистити пошук",
        "admin.pages.MarketPlacePage.search.empty": "Немає результату для \"{target}\"",
        "admin.pages.MarketPlacePage.search.placeholder": "Пошук",
        "admin.pages.MarketPlacePage.sort.alphabetical": "Алфавітний порядок",
        "admin.pages.MarketPlacePage.sort.alphabetical.selected": "Сортувати в алфавітному порядку",
        "admin.pages.MarketPlacePage.sort.githubStars": "Кількість зірок GitHub",
        "admin.pages.MarketPlacePage.sort.githubStars.selected": "Сортувати за зірками GitHub",
        "admin.pages.MarketPlacePage.sort.newest": "Найновіший",
        "admin.pages.MarketPlacePage.sort.newest.selected": "Сортувати за найновішим",
        "admin.pages.MarketPlacePage.sort.npmDownloads": "Кількість завантажень",
        "admin.pages.MarketPlacePage.sort.npmDownloads.selected": "Сортувати за завантаженнями npm",
        "admin.pages.MarketPlacePage.submit.plugin.link": "Надіслати розширення",
        "admin.pages.MarketPlacePage.submit.provider.link": "Надіслати провайдера",
        "admin.pages.MarketPlacePage.subtitle": "Отримати більше від Strapi",
        "admin.pages.MarketPlacePage.tab-group.label": "Розширення та постачальники для Strapi",
        "anErrorOccurred": "Ой! Щось пішло не так. Будь ласка спробуйте ще раз.",
        "app.component.CopyToClipboard.label": "Copy to clipboard",
        "app.component.search.label": "Search for {target}",
        "app.component.table.duplicate": "Duplicate {target}",
        "app.component.table.edit": "Edit {target}",
        "app.component.table.read": "Read {target}",
        "app.component.table.select.one-entry": "Select {target}",
        "app.component.table.view": "{target} details",
        "app.components.BlockLink.blog": "Blog",
        "app.components.BlockLink.blog.content": "Read the latest news about Strapi and the ecosystem.",
        "app.components.BlockLink.cloud": "Strapi Cloud",
        "app.components.BlockLink.cloud.content": "A fully composable, and collaborative platform to boost your team velocity.",
        "app.components.BlockLink.code": "Code examples",
        "app.components.BlockLink.code.content": "Learn by testing real projects developed the community.",
        "app.components.BlockLink.documentation.content": "Discover the essential concepts, guides and instructions.",
        "app.components.BlockLink.tutorial": "Tutorials",
        "app.components.BlockLink.tutorial.content": "Follow step-by-step instructions to use and customize Strapi.",
        "app.components.Button.cancel": "Cancel",
        "app.components.Button.confirm": "Confirm",
        "app.components.Button.reset": "Reset",
        "app.components.ComingSoonPage.comingSoon": "Coming soon",
        "app.components.ConfirmDialog.title": "Confirmation",
        "app.components.DownloadInfo.download": "Download in progress...",
        "app.components.DownloadInfo.text": "This could take a minute. Thanks for your patience.",
        "app.components.EmptyAttributes.title": "There are no fields yet",
        "app.components.EmptyStateLayout.content-document": "No content found",
        "app.components.EmptyStateLayout.content-permissions": "You don't have the permissions to access that content",
        "app.components.GuidedTour.CM.create.content": "<p>Create and manage all the content here in the Content Manager.</p><p>Ex: Taking the Blog website example further, one can write an Article, save and publish it as they like.</p><p>💡 Quick tip — Don't forget to hit publish on the content you create.</p>",
        "app.components.GuidedTour.CM.create.title": "⚡️ Create content",
        "app.components.GuidedTour.CM.success.content": "<p>Awesome, one last step to go!</p><b>🚀 See content in action</b>",
        "app.components.GuidedTour.CM.success.cta.title": "Test the API",
        "app.components.GuidedTour.CM.success.title": "Step 2: Completed ✅",
        "app.components.GuidedTour.CTB.create.content": "<p>Collection Types help you manage several entries, Single Types are suitable to manage only one entry.</p> <p>Ex: For a Blog website, Articles would be a Collection Type whereas a Homepage would be a Single Type.</p>",
        "app.components.GuidedTour.CTB.create.cta.title": "Build a Collection Type",
        "app.components.GuidedTour.CTB.create.title": "🧠 Create a first Collection Type",
        "app.components.GuidedTour.CTB.success.content": "<p>Good going!</p><b>⚡️ What would you like to share with the world?</b>",
        "app.components.GuidedTour.CTB.success.title": "Step 1: Completed ✅",
        "app.components.GuidedTour.apiTokens.create.content": "<p>Generate an authentication token here and retrieve the content you just created.</p>",
        "app.components.GuidedTour.apiTokens.create.cta.title": "Generate an API Token",
        "app.components.GuidedTour.apiTokens.create.title": "🚀 See content in action",
        "app.components.GuidedTour.apiTokens.success.content": "<p>See content in action by making an HTTP request:</p><ul><li><p>To this URL: <light>https://'<'YOUR_DOMAIN'>'/api/'<'YOUR_CT'>'</light></p></li><li><p>With the header: <light>Authorization: bearer '<'YOUR_API_TOKEN'>'</light></p></li></ul><p>For more ways to interact with content, see the <documentationLink>documentation</documentationLink>.</p>",
        "app.components.GuidedTour.apiTokens.success.cta.title": "Go back to homepage",
        "app.components.GuidedTour.apiTokens.success.title": "Step 3: Completed ✅",
        "app.components.GuidedTour.create-content": "Create content",
        "app.components.GuidedTour.home.CM.title": "⚡️ What would you like to share with the world?",
        "app.components.GuidedTour.home.CTB.cta.title": "Go to the Content type Builder",
        "app.components.GuidedTour.home.CTB.title": "🧠 Build the content structure",
        "app.components.GuidedTour.home.apiTokens.cta.title": "Test the API",
        "app.components.GuidedTour.skip": "Skip the tour",
        "app.components.GuidedTour.title": "3 steps to get started",
        "app.components.HomePage.button.blog": "See more on the blog",
        "app.components.HomePage.community": "Join the community",
        "app.components.HomePage.community.content": "Discuss with team members, contributors and developers on different channels.",
        "app.components.HomePage.create": "Create your first Content type",
        "app.components.HomePage.roadmap": "See our roadmap",
        "app.components.HomePage.welcome": "Welcome on board 👋",
        "app.components.HomePage.welcome.again": "Welcome 👋",
        "app.components.HomePage.welcomeBlock.content": "Congrats! You are logged as the first administrator. To discover the powerful features provided by Strapi, we recommend you to create your first Content type!",
        "app.components.HomePage.welcomeBlock.content.again": "We hope you are making progress on your project! Feel free to read the latest news about Strapi. We are giving our best to improve the product based on your feedback.",
        "app.components.HomePage.welcomeBlock.content.issues": "issues.",
        "app.components.HomePage.welcomeBlock.content.raise": " or raise ",
        "app.components.ImgPreview.hint": "Drag & drop your file into this area or {browse} for a file to upload",
        "app.components.ImgPreview.hint.browse": "browse",
        "app.components.InputFile.newFile": "Add new file",
        "app.components.InputFileDetails.open": "Open in a new tab",
        "app.components.InputFileDetails.originalName": "Original name:",
        "app.components.InputFileDetails.remove": "Remove this file",
        "app.components.InputFileDetails.size": "Size:",
        "app.components.InstallPluginPage.Download.description": "It might take a few seconds to download and install the plugin.",
        "app.components.InstallPluginPage.Download.title": "Downloading...",
        "app.components.InstallPluginPage.description": "Extend your app effortlessly.",
        "app.components.LeftMenu.collapse": "Collapse the navbar",
        "app.components.LeftMenu.expand": "Expand the navbar",
        "app.components.LeftMenu.general": "General",
        "app.components.LeftMenu.logo.alt": "Application logo",
        "app.components.LeftMenu.logout": "Logout",
        "app.components.LeftMenu.navbrand.title": "Strapi Dashboard",
        "app.components.LeftMenu.navbrand.workplace": "Workplace",
        "app.components.LeftMenu.plugins": "Plugins",
        "app.components.LeftMenuFooter.help": "Help",
        "app.components.LeftMenuFooter.poweredBy": "Powered by ",
        "app.components.LeftMenuLinkContainer.collectionTypes": "Collection Types",
        "app.components.LeftMenuLinkContainer.configuration": "Configurations",
        "app.components.LeftMenuLinkContainer.general": "General",
        "app.components.LeftMenuLinkContainer.noPluginsInstalled": "No plugins installed yet",
        "app.components.LeftMenuLinkContainer.plugins": "Plugins",
        "app.components.LeftMenuLinkContainer.singleTypes": "Single Types",
        "app.components.ListPluginsPage.deletePlugin.description": "It might take a few seconds to uninstall the plugin.",
        "app.components.ListPluginsPage.deletePlugin.title": "Uninstalling",
        "app.components.ListPluginsPage.description": "List of the installed plugins in the project.",
        "app.components.ListPluginsPage.helmet.title": "List plugins",
        "app.components.Logout.logout": "Logout",
        "app.components.Logout.profile": "Profile",
        "app.components.MarketplaceBanner": "Discover plugins built by the community, and many more awesome things to kickstart your project, on Strapi Marketplace.",
        "app.components.MarketplaceBanner.image.alt": "A Strapi rocket logo",
        "app.components.MarketplaceBanner.link": "Check it out now",
        "app.components.NotFoundPage.back": "Back to homepage",
        "app.components.NotFoundPage.description": "Not Found",
        "app.components.Official": "Official",
        "app.components.Onboarding.help.button": "Help button",
        "app.components.Onboarding.label.completed": "% completed",
        "app.components.Onboarding.link.build-content": "Build a content architecture",
        "app.components.Onboarding.link.manage-content": "Add & manage content",
        "app.components.Onboarding.link.manage-media": "Manage media",
        "app.components.Onboarding.link.more-videos": "Watch more videos",
        "app.components.Onboarding.title": "Get Started Videos",
        "app.components.PluginCard.Button.label.download": "Download",
        "app.components.PluginCard.Button.label.install": "Already installed",
        "app.components.PluginCard.PopUpWarning.install.impossible.autoReload.needed": "The autoReload feature needs to be enabled. Please start your app with `yarn develop`.",
        "app.components.PluginCard.PopUpWarning.install.impossible.confirm": "I understand!",
        "app.components.PluginCard.PopUpWarning.install.impossible.environment": "For security reasons, a plugin can only be downloaded in a development environment.",
        "app.components.PluginCard.PopUpWarning.install.impossible.title": "Downloading is impossible",
        "app.components.PluginCard.compatible": "Compatible with your app",
        "app.components.PluginCard.compatibleCommunity": "Compatible with the community",
        "app.components.PluginCard.more-details": "More details",
        "app.components.ToggleCheckbox.off-label": "False",
        "app.components.ToggleCheckbox.on-label": "True",
        "app.components.Users.MagicLink.connect": "Copy and share this link to give access to this user",
        "app.components.Users.MagicLink.connect.sso": "Send this link to the user, the first login can be made via a SSO provider",
        "app.components.Users.ModalCreateBody.block-title.details": "User details",
        "app.components.Users.ModalCreateBody.block-title.roles": "User's roles",
        "app.components.Users.ModalCreateBody.block-title.roles.description": "A user can have one or several roles",
        "app.components.Users.SortPicker.button-label": "Sort by",
        "app.components.Users.SortPicker.sortby.email_asc": "Email (A to Z)",
        "app.components.Users.SortPicker.sortby.email_desc": "Email (Z to A)",
        "app.components.Users.SortPicker.sortby.firstname_asc": "First name (A to Z)",
        "app.components.Users.SortPicker.sortby.firstname_desc": "First name (Z to A)",
        "app.components.Users.SortPicker.sortby.lastname_asc": "Last name (A to Z)",
        "app.components.Users.SortPicker.sortby.lastname_desc": "Last name (Z to A)",
        "app.components.Users.SortPicker.sortby.username_asc": "Username (A to Z)",
        "app.components.Users.SortPicker.sortby.username_desc": "Username (Z to A)",
        "app.components.listPlugins.button": "Add New Plugin",
        "app.components.listPlugins.title.none": "No plugins installed",
        "app.components.listPluginsPage.deletePlugin.error": "An error occurred while uninstalling the plugin",
        "app.containers.App.notification.error.init": "An error occurred while requesting the API",
        "app.containers.AuthPage.ForgotPasswordSuccess.text.contact-admin": "If you do not receive this link, please contact your administrator.",
        "app.containers.AuthPage.ForgotPasswordSuccess.text.email": "It can take a few minutes to receive your password recovery link.",
        "app.containers.AuthPage.ForgotPasswordSuccess.title": "Email sent",
        "app.containers.Users.EditPage.form.active.label": "Active",
        "app.containers.Users.EditPage.header.label": "Edit {name}",
        "app.containers.Users.EditPage.header.label-loading": "Edit user",
        "app.containers.Users.EditPage.roles-bloc-title": "Attributed roles",
        "app.containers.Users.ModalForm.footer.button-success": "Invite user",
        "app.links.configure-view": "Configure the view",
        "app.page.not.found": "Oops! We can't seem to find the page you're looking for...",
        "app.static.links.cheatsheet": "CheatSheet",
        "app.utils.SelectOption.defaultMessage": " ",
        "app.utils.add-filter": "Add filter",
        "app.utils.close-label": "Close",
        "app.utils.defaultMessage": " ",
        "app.utils.delete": "Delete",
        "app.utils.duplicate": "Duplicate",
        "app.utils.edit": "Edit",
        "app.utils.errors.file-too-big.message": "The file is too big",
        "app.utils.filter-value": "Filter value",
        "app.utils.filters": "Filters",
        "app.utils.notify.data-loaded": "The {target} has loaded",
        "app.utils.placeholder.defaultMessage": " ",
        "app.utils.publish": "Publish",
        "app.utils.select-all": "Select all",
        "app.utils.select-field": "Select field",
        "app.utils.select-filter": "Select filter",
        "app.utils.unpublish": "Unpublish",
        "clearLabel": "Clear",
        "coming.soon": "This content is currently under construction and will be back in a few weeks!",
        "component.Input.error.validation.integer": "The value must be an integer",
        "components.AutoReloadBlocker.description": "Run Strapi with one of the following commands:",
        "components.AutoReloadBlocker.header": "Reload feature is required for this plugin.",
        "components.ErrorBoundary.title": "Something went wrong...",
        "components.FilterOptions.FILTER_TYPES.$contains": "contains (case sensitive)",
        "components.FilterOptions.FILTER_TYPES.$endsWith": "ends with",
        "components.FilterOptions.FILTER_TYPES.$eq": "is",
        "components.FilterOptions.FILTER_TYPES.$gt": "is greater than",
        "components.FilterOptions.FILTER_TYPES.$gte": "is greater than or equal to",
        "components.FilterOptions.FILTER_TYPES.$lt": "is lower than",
        "components.FilterOptions.FILTER_TYPES.$lte": "is lower than or equal to",
        "components.FilterOptions.FILTER_TYPES.$ne": "is not",
        "components.FilterOptions.FILTER_TYPES.$notContains": "does not contain (case sensitive)",
        "components.FilterOptions.FILTER_TYPES.$notNull": "is not null",
        "components.FilterOptions.FILTER_TYPES.$null": "is null",
        "components.FilterOptions.FILTER_TYPES.$startsWith": "starts with",
        "components.Input.error.attribute.key.taken": "This value already exists",
        "components.Input.error.attribute.sameKeyAndName": "Can't be equal",
        "components.Input.error.attribute.taken": "This field name already exists",
        "components.Input.error.contain.lowercase": "Password must contain at least one lowercase character",
        "components.Input.error.contain.number": "Password must contain at least one number",
        "components.Input.error.contain.uppercase": "Password must contain at least one uppercase character",
        "components.Input.error.contentTypeName.taken": "This name already exists",
        "components.Input.error.custom-error": "{errorMessage} ",
        "components.Input.error.password.noMatch": "Passwords do not match",
        "components.Input.error.validation.email": "This is an invalid email",
        "components.Input.error.validation.json": "This doesn't match the JSON format",
        "components.Input.error.validation.lowercase": "The value must be a lowercase string",
        "components.Input.error.validation.max": "The value is too high.",
        "components.Input.error.validation.maxLength": "The value is too long.",
        "components.Input.error.validation.min": "The value is too low.",
        "components.Input.error.validation.minLength": "The value is too short.",
        "components.Input.error.validation.minSupMax": "Can't be superior",
        "components.Input.error.validation.regex": "The value does not match the regex.",
        "components.Input.error.validation.required": "This value is required.",
        "components.Input.error.validation.unique": "This value is already used.",
        "components.InputSelect.option.placeholder": "Choose here",
        "components.ListRow.empty": "There is no data to be shown.",
        "components.NotAllowedInput.text": "No permissions to see this field",
        "components.OverlayBlocker.description": "You're using a feature that needs the server to restart. Please wait until the server is up.",
        "components.OverlayBlocker.description.serverError": "The server should have restarted, please check your logs in the terminal.",
        "components.OverlayBlocker.title": "Waiting for restart...",
        "components.OverlayBlocker.title.serverError": "The restart is taking longer than expected",
        "components.PageFooter.select": "Entries per page",
        "components.ProductionBlocker.description": "For safety purposes we have to disable this plugin in other environments.",
        "components.ProductionBlocker.header": "This plugin is only available in development.",
        "components.Search.placeholder": "Search...",
        "components.TableHeader.sort": "Sort on {label}",
        "components.Wysiwyg.ToggleMode.markdown-mode": "Markdown mode",
        "components.Wysiwyg.ToggleMode.preview-mode": "Preview mode",
        "components.Wysiwyg.collapse": "Collapse",
        "components.Wysiwyg.selectOptions.H1": "Title H1",
        "components.Wysiwyg.selectOptions.H2": "Title H2",
        "components.Wysiwyg.selectOptions.H3": "Title H3",
        "components.Wysiwyg.selectOptions.H4": "Title H4",
        "components.Wysiwyg.selectOptions.H5": "Title H5",
        "components.Wysiwyg.selectOptions.H6": "Title H6",
        "components.Wysiwyg.selectOptions.title": "Add a title",
        "components.WysiwygBottomControls.charactersIndicators": "characters",
        "components.WysiwygBottomControls.fullscreen": "Expand",
        "components.WysiwygBottomControls.uploadFiles": "Drag & drop files, paste from the clipboard or {browse}.",
        "components.WysiwygBottomControls.uploadFiles.browse": "select them",
        "components.pagination.go-to": "Go to page {page}",
        "components.pagination.go-to-next": "Go to next page",
        "components.pagination.go-to-previous": "Go to previous page",
        "components.pagination.remaining-links": "And {number} other links",
        "components.popUpWarning.button.cancel": "No, cancel",
        "components.popUpWarning.button.confirm": "Yes, confirm",
        "components.popUpWarning.message": "Are you sure you want to delete this?",
        "components.popUpWarning.title": "Please confirm",
        "content-manager.App.schemas.data-loaded": "The schemas have been successfully loaded",
        "content-manager.DynamicTable.relation-loaded": "Relations have been loaded",
        "content-manager.DynamicTable.relation-loading": "Relations are loading",
        "content-manager.DynamicTable.relation-more": "This relation contains more entities than displayed",
        "content-manager.EditRelations.title": "Relational data",
        "content-manager.HeaderLayout.button.label-add-entry": "Create new entry",
        "content-manager.api.id": "API ID",
        "content-manager.apiError.This attribute must be unique": "{field} must be unique",
        "content-manager.components.AddFilterCTA.add": "Filters",
        "content-manager.components.AddFilterCTA.hide": "Filters",
        "content-manager.components.DragHandle-label": "Drag",
        "content-manager.components.DraggableAttr.edit": "Click to edit",
        "content-manager.components.DraggableCard.delete.field": "Delete {item}",
        "content-manager.components.DraggableCard.edit.field": "Edit {item}",
        "content-manager.components.DraggableCard.move.field": "Move {item}",
        "content-manager.components.DynamicTable.row-line": "item line {number}",
        "content-manager.components.DynamicZone.ComponentPicker-label": "Pick one component",
        "content-manager.components.DynamicZone.add-component": "Add a component to {componentName}",
        "content-manager.components.DynamicZone.delete-label": "Delete {name}",
        "content-manager.components.DynamicZone.error-message": "The component contains error(s)",
        "content-manager.components.DynamicZone.missing-components": "There {number, plural, =0 {are # missing components} one {is # missing component} other {are # missing components}}",
        "content-manager.components.DynamicZone.move-down-label": "Move component down",
        "content-manager.components.DynamicZone.move-up-label": "Move component up",
        "content-manager.components.DynamicZone.pick-compo": "Pick one component",
        "content-manager.components.DynamicZone.required": "Component is required",
        "content-manager.components.EmptyAttributesBlock.button": "Go to settings page",
        "content-manager.components.EmptyAttributesBlock.description": "You can change your settings",
        "content-manager.components.FieldItem.linkToComponentLayout": "Set the component's layout",
        "content-manager.components.FieldSelect.label": "Add a field",
        "content-manager.components.FilterOptions.button.apply": "Apply",
        "content-manager.components.FiltersPickWrapper.PluginHeader.actions.apply": "Apply",
        "content-manager.components.FiltersPickWrapper.PluginHeader.actions.clearAll": "Clear all",
        "content-manager.components.FiltersPickWrapper.PluginHeader.description": "Set the conditions to apply to filter the entries",
        "content-manager.components.FiltersPickWrapper.PluginHeader.title.filter": "Filters",
        "content-manager.components.FiltersPickWrapper.hide": "Hide",
        "content-manager.components.LeftMenu.Search.label": "Search for a content type",
        "content-manager.components.LeftMenu.collection-types": "Collection Types",
        "content-manager.components.LeftMenu.single-types": "Single Types",
        "content-manager.components.LimitSelect.itemsPerPage": "Items per page",
        "content-manager.components.NotAllowedInput.text": "No permissions to see this field",
        "content-manager.components.RelationInput.icon-button-aria-label": "Drag",
        "content-manager.components.RepeatableComponent.error-message": "The component(s) contain error(s)",
        "content-manager.components.Search.placeholder": "Search for an entry...",
        "content-manager.components.Select.draft-info-title": "State: Draft",
        "content-manager.components.Select.publish-info-title": "State: Published",
        "content-manager.components.SettingsViewWrapper.pluginHeader.description.edit-settings": "Customize how the edit view will look like.",
        "content-manager.components.SettingsViewWrapper.pluginHeader.description.list-settings": "Define the settings of the list view.",
        "content-manager.components.SettingsViewWrapper.pluginHeader.title": "Configure the view — {name}",
        "content-manager.components.TableDelete.delete": "Delete all",
        "content-manager.components.TableDelete.deleteSelected": "Delete selected",
        "content-manager.components.TableDelete.label": "{number, plural, one {# entry} other {# entries}} selected",
        "content-manager.components.TableEmpty.withFilters": "There are no {contentType} with the applied filters...",
        "content-manager.components.TableEmpty.withSearch": "There are no {contentType} corresponding to the search ({search})...",
        "content-manager.components.TableEmpty.withoutFilter": "There are no {contentType}...",
        "content-manager.components.empty-repeatable": "No entry yet. Click on the button below to add one.",
        "content-manager.components.notification.info.maximum-requirement": "You have already reached the maximum number of fields",
        "content-manager.components.notification.info.minimum-requirement": "A field has been added to match the minimum requirement",
        "content-manager.components.repeatable.reorder.error": "An error occurred while reordering your component's field, please try again",
        "content-manager.components.reset-entry": "Reset entry",
        "content-manager.components.uid.apply": "apply",
        "content-manager.components.uid.available": "Available",
        "content-manager.components.uid.regenerate": "Regenerate",
        "content-manager.components.uid.suggested": "suggested",
        "content-manager.components.uid.unavailable": "Unavailable",
        "content-manager.containers.Edit.Link.Layout": "Configure the layout",
        "content-manager.containers.Edit.Link.Model": "Edit the Collection-Type",
        "content-manager.containers.Edit.addAnItem": "Add an item...",
        "content-manager.containers.Edit.clickToJump": "Click to jump to the entry",
        "content-manager.containers.Edit.delete": "Delete",
        "content-manager.containers.Edit.delete-entry": "Delete this entry",
        "content-manager.containers.Edit.editing": "Editing...",
        "content-manager.containers.Edit.information": "Information",
        "content-manager.containers.Edit.information.by": "By",
        "content-manager.containers.Edit.information.created": "Created",
        "content-manager.containers.Edit.information.draftVersion": "draft version",
        "content-manager.containers.Edit.information.editing": "Editing",
        "content-manager.containers.Edit.information.lastUpdate": "Last update",
        "content-manager.containers.Edit.information.publishedVersion": "published version",
        "content-manager.containers.Edit.pluginHeader.title.new": "Create an entry",
        "content-manager.containers.Edit.reset": "Reset",
        "content-manager.containers.Edit.returnList": "Return to list",
        "content-manager.containers.Edit.seeDetails": "Details",
        "content-manager.containers.Edit.submit": "Save",
        "content-manager.containers.EditSettingsView.modal-form.edit-field": "Edit the field",
        "content-manager.containers.EditView.add.new-entry": "Add an entry",
        "content-manager.containers.EditView.notification.errors": "The form contains some errors",
        "content-manager.containers.Home.introduction": "To edit your entries go to the specific link in the left menu. This plugin doesn't have a proper way to edit settings and it's still under active development.",
        "content-manager.containers.Home.pluginHeaderDescription": "Manage your entries through a powerful and beautiful interface.",
        "content-manager.containers.Home.pluginHeaderTitle": "Менеджер Вмісту",
        "content-manager.containers.List.draft": "Draft",
        "content-manager.containers.List.errorFetchRecords": "Error",
        "content-manager.containers.List.published": "Published",
        "content-manager.containers.ListPage.displayedFields": "Displayed Fields",
        "content-manager.containers.ListPage.items": "{number, plural, =0 {items} one {item} other {items}}",
        "content-manager.containers.ListPage.table-headers.publishedAt": "State",
        "content-manager.containers.ListSettingsView.modal-form.edit-label": "Edit {fieldName}",
        "content-manager.containers.SettingPage.add.field": "Insert another field",
        "content-manager.containers.SettingPage.add.relational-field": "Insert another related field",
        "content-manager.containers.SettingPage.attributes": "Attributes fields",
        "content-manager.containers.SettingPage.attributes.description": "Define the order of the attributes",
        "content-manager.containers.SettingPage.editSettings.description": "Drag & drop the fields to build the layout",
        "content-manager.containers.SettingPage.editSettings.entry.title": "Entry title",
        "content-manager.containers.SettingPage.editSettings.entry.title.description": "Set the displayed field of your entry",
        "content-manager.containers.SettingPage.editSettings.relation-field.description": "Set the displayed field in both the edit and list views",
        "content-manager.containers.SettingPage.editSettings.title": "Edit view (settings)",
        "content-manager.containers.SettingPage.layout": "Layout",
        "content-manager.containers.SettingPage.listSettings.description": "Configure the options for this Collection Type",
        "content-manager.containers.SettingPage.listSettings.title": "List view (settings)",
        "content-manager.containers.SettingPage.pluginHeaderDescription": "Configure the specific settings for this Collection Type",
        "content-manager.containers.SettingPage.relations": "Пов’язані поля",
        "content-manager.containers.SettingPage.settings": "Налаштування",
        "content-manager.containers.SettingPage.view": "Вид",
        "content-manager.containers.SettingViewModel.pluginHeader.title": "Content Manager — {name}",
        "content-manager.containers.SettingsPage.Block.contentType.description": "Configure the specific settings",
        "content-manager.containers.SettingsPage.Block.contentType.title": "Collection Types",
        "content-manager.containers.SettingsPage.Block.generalSettings.description": "Configure the default options for your Collection Types",
        "content-manager.containers.SettingsPage.Block.generalSettings.title": "General",
        "content-manager.containers.SettingsPage.pluginHeaderDescription": "Configure the settings for all your Collection Types and Groups",
        "content-manager.containers.SettingsView.list.subtitle": "Configure the layout and display of your Collection Types and Groups",
        "content-manager.containers.SettingsView.list.title": "Display configurations",
        "content-manager.dnd.cancel-item": "{item}, dropped. Re-order cancelled.",
        "content-manager.dnd.drop-item": "{item}, dropped. Final position in list: {position}.",
        "content-manager.dnd.grab-item": "{item}, grabbed. Current position in list: {position}. Press up and down arrow to change position, Spacebar to drop, Escape to cancel.",
        "content-manager.dnd.instructions": "Натисніть пробіл, щоб захопити та змінити порядок",
        "content-manager.dnd.reorder": "{item}, переміщено. Нова позиція в списку: {position}.",
        "content-manager.edit-settings-view.link-to-ctb.components": "Відредагувати компонент",
        "content-manager.edit-settings-view.link-to-ctb.content-types": "Відредагувати тип вмісту",
        "content-manager.emptyAttributes.button": "Перейти до конструктора типу колекції",
        "content-manager.emptyAttributes.description": "Додайте своє перше поле до типу колекції",
        "content-manager.emptyAttributes.title": "Полів ще немає",
        "content-manager.error.attribute.key.taken": "This value already exists",
        "content-manager.error.attribute.sameKeyAndName": "Не можуть бути рівними",
        "content-manager.error.attribute.taken": "Ця назва поля вже існує",
        "content-manager.error.contentTypeName.taken": "Це ім'я вже існує",
        "content-manager.error.model.fetch": "Під час отримання конфігурації моделі сталася помилка.",
        "content-manager.error.record.create": "Під час створення запису сталася помилка.",
        "content-manager.error.record.delete": "Під час видалення запису сталася помилка.",
        "content-manager.error.record.fetch": "Під час отримання запису сталася помилка.",
        "content-manager.error.record.update": "Під час оновлення запису сталася помилка.",
        "content-manager.error.records.count": "Під час отримання записів підрахунку сталася помилка.",
        "content-manager.error.records.fetch": "Під час отримання записів сталася помилка.",
        "content-manager.error.schema.generation": "Під час створення схеми сталася помилка.",
        "content-manager.error.validation.json": "Це не JSON",
        "content-manager.error.validation.max": "Значення завелике.",
        "content-manager.error.validation.maxLength": "Значення задовге.",
        "content-manager.error.validation.min": "Значення занизьке.",
        "content-manager.error.validation.minLength": "Значення закоротке.",
        "content-manager.error.validation.minSupMax": "Не може бути вищим",
        "content-manager.error.validation.regex": "Значення не відповідає регулярному виразу.",
        "content-manager.error.validation.required": "Необхідно ввести це значення.",
        "content-manager.form.Input.bulkActions": "Увімкнути групові дії",
        "content-manager.form.Input.defaultSort": "Атрибут сортування за замовчуванням",
        "content-manager.form.Input.description": "Опис",
        "content-manager.form.Input.description.placeholder": "Відображати ім'я в профілі",
        "content-manager.form.Input.editable": "Поле для редагування",
        "content-manager.form.Input.filters": "Увімкнути фільтри",
        "content-manager.form.Input.hint.character.unit": "{maxValue, plural, one { character} other { characters}}",
        "content-manager.form.Input.hint.minMaxDivider": " / ",
        "content-manager.form.Input.hint.text": "{min, select, undefined {} other {min. {min}}}{divider}{max, select, undefined {} other {max. {max}}}{unit}{br}{description}",
        "content-manager.form.Input.label": "Ярлик",
        "content-manager.form.Input.label.inputDescription": "Це значення перекриває ярлик, що відображається в заголовку таблиці",
        "content-manager.form.Input.pageEntries": "Записів на сторінці",
        "content-manager.form.Input.pageEntries.inputDescription": "Примітка. Ви можете змінити це значення на сторінці налаштувань типу колекції.",
        "content-manager.form.Input.placeholder": "Заповнювач",
        "content-manager.form.Input.placeholder.placeholder": "Моє чудове значення",
        "content-manager.form.Input.search": "Увімкнути пошук",
        "content-manager.form.Input.search.field": "Увімкнути пошук в цьому полі",
        "content-manager.form.Input.sort.field": "Увімкнути сортування в цьому полі",
        "content-manager.form.Input.sort.order": "Порядок сортування за замовчуванням",
        "content-manager.form.Input.wysiwyg": "Відображати як WYSIWYG",
        "content-manager.global.displayedFields": "Відображені поля",
        "content-manager.groups": "Групи",
        "content-manager.groups.numbered": "Групи ({number})",
        "content-manager.header.name": "Вміст",
        "content-manager.link-to-ctb": "Відредагувати модель",
        "content-manager.models": "Типи колекцій",
        "content-manager.models.numbered": "Типи колекцій ({number})",
        "content-manager.notification.error.displayedFields": "Потрібно принаймні одне відображене поле",
        "content-manager.notification.error.relationship.fetch": "Сталася помилка під час отримання зв’язку.",
        "content-manager.notification.info.SettingPage.disableSort": "Потрібно мати один атрибут із дозволеним сортуванням",
        "content-manager.notification.info.minimumFields": "Ви повинні мати принаймні одне поле",
        "content-manager.notification.upload.error": "Під час завантаження ваших файлів сталася помилка",
        "content-manager.pageNotFound": "Сторінку не знайдено",
        "content-manager.pages.ListView.header-subtitle": "{number, plural, =0 {# entries} one {# entry} other {# entries}} знайдено",
        "content-manager.pages.NoContentType.button": "Створіть свій перший тип вмісту",
        "content-manager.pages.NoContentType.text": "У вас ще немає вмісту, рекомендуємо вам створити свій перший тип вмісту.",
        "content-manager.permissions.not-allowed.create": "Вам заборонено створювати документ",
        "content-manager.permissions.not-allowed.update": "Вам заборонено переглядати цей документ",
        "content-manager.plugin.description.long": "Швидкий спосіб перегляду, редагування та видалення даних у вашій базі даних.",
        "content-manager.plugin.description.short": "Швидкий спосіб перегляду, редагування та видалення даних у вашій базі даних.",
        "content-manager.popUpWarning.bodyMessage.contentType.delete": "Ви впевнені, що хочете видалити тип вмісту?",
        "content-manager.popUpWarning.bodyMessage.contentType.delete.all": "Ви впевнені, що хочете видалити всі типи вмісту?",
        "content-manager.popUpWarning.warning.has-draft-relations.title": "Підтвердження",
        "content-manager.popUpWarning.warning.publish-question": "Ви все ще хочете опублікувати?",
        "content-manager.popUpWarning.warning.unpublish": "Якщо ви не опублікуєте цей вміст, він автоматично перетвориться на чернетку.",
        "content-manager.popUpWarning.warning.unpublish-question": "Ви впевнені, що не хочете це публікувати?",
        "content-manager.popUpWarning.warning.updateAllSettings": "Це змінить усі ваші налаштування",
        "content-manager.popUpwarning.warning.has-draft-relations.button-confirm": "Так, опублікувати",
        "content-manager.popUpwarning.warning.has-draft-relations.message": "<b>{count, plural, one { відношення є } other { відношення є } }</b> ще не опубліковано та може призвести до неочікуваної поведінки.",
        "content-manager.popover.display-relations.label": "Показати відносини",
        "content-manager.relation.add": "Додайте відношення",
        "content-manager.relation.disconnect": "Видалити",
        "content-manager.relation.isLoading": "Відносини завантажуються",
        "content-manager.relation.loadMore": "Завантажити ще",
        "content-manager.relation.notAvailable": "Відносини відсутні",
        "content-manager.relation.publicationState.draft": "Чернетка",
        "content-manager.relation.publicationState.published": "Опубліковано",
        "content-manager.reviewWorkflows.stage.label": "Етап огляду",
        "content-manager.select.currently.selected": "{count} зараз вибрано",
        "content-manager.success.record.delete": "Видалено",
        "content-manager.success.record.publish": "Опубліковано",
        "content-manager.success.record.save": "Збережено",
        "content-manager.success.record.unpublish": "Неопубліковано",
        "content-manager.utils.data-loaded": "{number, plural, =1 {entry has} other {entries have}} успішно завантажено",
        "dark": "Темний",
        "form.button.continue": "Продовжити",
        "form.button.done": "Готово",
        "global.actions": "Дії",
        "global.auditLogs": "Журнали аудиту",
        "global.back": "Назад",
        "global.cancel": "Скасувати",
        "global.change-password": "Змінити пароль",
        "global.content-manager": "Менеджер Вмісту",
        "global.continue": "Продовжити",
        "global.delete": "Видалити",
        "global.delete-target": "Видалити {target}",
        "global.description": "Опис",
        "global.details": "Подробиці",
        "global.disabled": "Вимкнено",
        "global.documentation": "Документація",
        "global.enabled": "Увімкнено",
        "global.finish": "Закінчити",
        "global.marketplace": "Маркетплейс",
        "global.name": "Ім'я",
        "global.none": "Жодного",
        "global.password": "Пароль",
        "global.plugins": "Розширення",
        "global.plugins.content-manager": "Менеджер Вмісту",
        "global.plugins.content-manager.description": "Швидкий спосіб перегляду, редагування та видалення даних у вашій базі даних.",
        "global.plugins.content-type-builder": "Конструктор типів вмісту",
        "global.plugins.content-type-builder.description": "Змоделюйте структуру даних вашого API. Створіть нові поля та відносини всього за хвилину. Файли автоматично створюються та оновлюються у вашому проекті.",
        "global.plugins.documentation": "Документація",
        "global.plugins.documentation.description": "Створіть документ OpenAPI та візуалізуйте свій API за допомогою SWAGGER UI.",
        "global.plugins.email": "Email",
        "global.plugins.email.description": "Налаштуйте програму для надсилання електронних листів.",
        "global.plugins.graphql": "GraphQL",
        "global.plugins.graphql.description": "Додати кінцеву точку GraphQL із стандартними методами API.",
        "global.plugins.i18n": "Інтернаціоналізація",
        "global.plugins.i18n.description": "Цей плагін дозволяє створювати, читати та оновлювати вміст різними мовами як з панелі адміністратора, так і з API.",
        "global.plugins.sentry": "Sentry",
        "global.plugins.sentry.description": "Надсилати події помилок Strapi до Sentry.",
        "global.plugins.upload": "Медіатека",
        "global.plugins.upload.description": "Керування медіафайлами.",
        "global.plugins.users-permissions": "Ролі та дозволи",
        "global.plugins.users-permissions.description": "Захистіть свій API за допомогою процесу повної автентифікації на основі JWT. Цей плагін також постачається зі стратегією ACL, яка дозволяє вам керувати дозволами між групами користувачів.",
        "global.profile": "Профіль",
        "global.prompt.unsaved": "Ви впевнені, що бажаєте залишити цю сторінку? Усі ваші зміни буде втрачено",
        "global.reset-password": "Скинути пароль",
        "global.roles": "Ролі",
        "global.save": "Зберегти",
        "global.search": "Пошук",
        "global.see-more": "Побачити більше",
        "global.select": "Виберіть",
        "global.select-all-entries": "Виберіть усі записи",
        "global.settings": "Налаштування",
        "global.type": "Тип",
        "global.users": "Користувачі",
        "light": "Світлий",
        "notification.contentType.relations.conflict": "Тип вмісту має конфліктні відносини",
        "notification.default.title": "Інформація:",
        "notification.ee.warning.at-seat-limit.title": "{licenseLimitStatus, select, OVER_LIMIT {Over} AT_LIMIT {At}} обмеження кількості місць ({currentUserCount}/{permittedSeats})",
        "notification.ee.warning.over-.message": "Додайте місця до {licenseLimitStatus, select, OVER_LIMIT {invite} AT_LIMIT {re-enable}} Users. Якщо ви вже це зробили, але це ще не відображено в Strapi, обов’язково перезапустіть програму.",
        "notification.error": "Виникла помилка",
        "notification.error.invalid.configuration": "У вас неправильна конфігурація, перевірте журнал свого сервера для отримання додаткової інформації.",
        "notification.error.layout": "Не вдалося отримати макет",
        "notification.error.tokennamenotunique": "Ім’я вже призначено іншому токену",
        "notification.form.error.fields": "Форма містить деякі помилки",
        "notification.form.success.fields": "Зміни збережено",
        "notification.link-copied": "Посилання скопійовано в буфер обміну",
        "notification.permission.not-allowed-read": "Вам заборонено переглядати цей документ",
        "notification.success.apitokencreated": "Токен API успішно створено",
        "notification.success.apitokenedited": "API токен успішно відредаговано",
        "notification.success.delete": "Елемент видалено",
        "notification.success.saved": "Збережено",
        "notification.success.title": "Успіх:",
        "notification.success.transfertokencreated": "Токен передачі успішно створено",
        "notification.success.transfertokenedited": "Токен передачі успішно відредаговано",
        "notification.version.update.message": "Доступна нова версія Strapi!",
        "notification.warning.404": "404 - Не знайдено",
        "notification.warning.title": "Увага:",
        "or": "АБО",
        "request.error.model.unknown": "Цієї моделі не існує",
        "selectButtonTitle": "Виберіть",
        "skipToContent": "Перейти до вмісту",
        "submit": "Надіслати"
      }
      
    }
  },
  bootstrap(app) {
    console.log(app);
  },
};
